### ISSUE TITLE
Non-portable tests

### ISSUE THREAD

**Issue by Marckvdv** [glium/glium#1113]
Some tests depend on functions that may work differently on different machines. One of these functions is: `Texture2d::empty` and other functions like this one which don't specify a specific pixel format.

2 of these test are:

`uniforms_storage_ignore_inactive_uniforms`
`uniforms_storage_single_value`

I'm pretty sure there are more of these, though I will try to add them later.

**Comment by spearman** [comment]
Test failures:
```
failures:

---- uniforms_storage_ignore_inactive_uniforms stdout ----
thread 'uniforms_storage_ignore_inactive_uniforms' panicked at tests/uniforms.rs:136:5:
assertion `left == right` failed
  left: (255, 0, 0, 127)
 right: (255, 0, 0, 128)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- uniforms_dynamic_ignore_inactive_uniforms stdout ----
thread 'uniforms_dynamic_ignore_inactive_uniforms' panicked at tests/uniforms.rs:299:5:
assertion `left == right` failed
  left: (255, 0, 0, 127)
 right: (255, 0, 0, 128)

---- uniforms_storage_single_value stdout ----
thread 'uniforms_storage_single_value' panicked at tests/uniforms.rs:54:5:
assertion `left == right` failed
  left: (255, 0, 0, 127)
 right: (255, 0, 0, 128)

---- uniforms_dynamic_single_value stdout ----
thread 'uniforms_dynamic_single_value' panicked at tests/uniforms.rs:215:5:
assertion `left == right` failed
  left: (255, 0, 0, 127)
 right: (255, 0, 0, 128)


failures:
    uniforms_dynamic_ignore_inactive_uniforms
    uniforms_dynamic_single_value
    uniforms_storage_ignore_inactive_uniforms
    uniforms_storage_single_value
```

**Comment by justincredible** [comment]
What system are you using?

I had these failures on Windows 10, so added https://github.com/glium/glium/blob/14cf7590037894140f5bea34174e7cd83ce6929d/tests/uniforms.rs#L8-L12

Depending on how granular this partition needs to go, it might be simpler to modify the assertion pairs to match one of the two values consistently for any system.

**Comment by spearman** [comment]
> What system are you using?

NixOS 24.05 - OpenGL 3.3.0 core NVIDIA 390.157 NVS 5400M/PCIe/SSE2
