### ISSUE TITLE
Picking example gives black screen

### ISSUE THREAD

**Issue by casey** [glium/glium#1538]
I get the following:

<img width="1136" alt="screen shot 2016-11-07 at 4 40 34 pm" src="https://cloud.githubusercontent.com/assets/1945/20082152/ecaa2292-a508-11e6-9400-dcb1ce33f151.png">

I'm on macOS 10.11.6.

Also, I think there's an off by one bug in the coordinate code, since I can trigger a panic by moving my mouse over the bottom of the window. I get the following error:

`thread 'main' panicked at 'attempt to subtract with overflow', src/picking.rs:216`

**Comment by Mufferaw** [comment]
Regarding the black screen, I think line 107 should read :
`camera.set_position((0.0, 0.0, -1.5));`

**Comment by Mufferaw** [comment]
Regarding the black screen, I think line 107 should read :
`camera.set_position((0.0, 0.0, -1.5));`

**Comment by est31** [comment]
Fixed by #1760 (7d5baa9f925010716bfffd0fba17ef42580d8177)

**Comment by est31** [comment]
Thanks @Mufferaw for the suggestion
