### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by dlight** [glium/glium#1554]
I just noticed that the documentation linked in README and on Cargo.toml doesn't display the `Error` trait that is implemented in 0.15 (and perhaps earlier versions), so it must be out of date.

A workaround is to link to [the docs on docs.rs](https://docs.rs/glium/0.15.0/glium/) (but the link needs to be bumped each release).

**Comment by daboross** [comment]
I believe this is fixed as of https://github.com/glium/glium/commit/85f5a7ef3b659f00e903ef63a7e5c625679c78ea.
