### ISSUE TITLE
Using Box<_> instead of &'a _ in Framebuffer objects

### ISSUE THREAD

**Issue by hashedone** [glium/glium#1576]
Implementing something similar to deffered shading, I stucked in place, where I needed to keep RenderBuffer in same place as FrameBuffer, like (simplified code here):
```
struct Prepass {
  color: glium::framebuffer::RenderBuffer,
  fb: glium::framebuffer::SimpleFramebuffer<???>
}
```
Obviously I can't create fb like this, because color cannot be borrowed to fb - it would borrow also Prepass, what's impossible. Also I see, that almost an year ago someone had the same problem, and he got no help here: #1475. On rust for begginers someone help me with dirty solution like this:
```
struct Prepass {
  color: Box<glium::framebuffer::RenderBuffer>,
  fb: Option<glium::framebuffer::SimpleFramebuffer<'static>>
}

unsafe fn extend_lifetime<'a, T>(x: &'a T) -> &'static T {
    std::mem::transmute::<&'a T, &'static T>(x)
}

impl Prepass {
  fn new<Facade: glium::backend::Facade>(facade: &Facade) { 
    let color = //... initialize color
    let color = Box::new(color);
    let fb = glium::framebuffer::SimpleFramebuffer::new(facade, extend_lifetime(&color));
    Prepass { color: color, fb: fb }
  }
}

impl Drop for Prepass {
  fn drop(mut& self) {
    let fb = self.fb.take();
  }
}
```
For now I would use this workaround, but actually being forced to use transmute for such common thing isn't best solution. I think that it is conciderable switching to boxed types instead explicit lifetimes (or at least make two parallel apis) to solve this problem.

**Comment by tomaka** [comment]
This is in fact a problem with the Rust language, and not with glium in particular.
However glium has a work-around.

Creating a `SimpleFramebuffer` puts the actual OpenGL framebuffer in a cache. When you recreate it later, it will load this framebuffer from the cache.

Therefore you don't need to store the `SimpleFramebuffer` in your struct. Just recreate it every time you need it.

**Comment by avl** [comment]
I think tomaka's workaround seems completely satisfactory. Maybe we can close this issue?
