### ISSUE TITLE
implement_vertex! does not disregard unused fields

### ISSUE THREAD

**Issue by sharazam** [glium/glium#1581]
If I have a struct like this:

```

#[derive(PartialEq, Copy, Clone, Debug)]
pub struct Point {
    pub x: f64,
    pub y: f64,
    pub srid: Option<i32>,
}
```

I try to implement vertex for this type:

`implement_vertex!(Point, x, y);`

I am not implementing the field srid, since it isn't of any interested and can't be implemented. However, the macro still creates space for it. Is it possible to let the macro disregard the field if it isn't specified?

If I try to create a Vertex and push it into a vertex buffer, it should disregard the field "srid". What actually happens is that for each Vertex, 8 extra bytes get allocated (for the srid):

```
let mut vertices = Vec::<Point>::new();
let test_point = Point { x: 3.123, y: 5.421094, srid: Some(4236) };
vertices.push(point);
let vbuf = glium::VertexBuffer::new(display, &vertices).unwrap();
println!("size of vertex buffer: {:?}", vbuf.get_size());
// is 24 bytes, should be 16 since I only specified x and y
```

Is this possible to do in a macro? Or am I using the macro wrong?

**Comment by sharazam** [comment]
This is something I just noticed - I can compile my application against the 0.16.0 release (three months ago). However, if I am trying to compile against master, it fails with the message "the trait "glium::Vertex" is not implemented for "types::osm_tuple::postgis::ewkb::Point"' - using the same code on my part (see above).

Which means that some commit within the last three months changed something about the Vertex trait or the implement_vertex! macro so that it fails integration in other crates.

**Comment by avl** [comment]
Maybe keeping the exact same struct size allows an efficient simple copy from host memory to graphics memory? Otherwise glium would have to skip 8 bytes for every source vertex and couldn't use a simple contiguous copy?

**Comment by tomaka** [comment]
There is a misunderstanding of the purpose of the macro.
In the example the buffer does contain a `Point` and will always contain a `Point`. The macro only makes it possible to use the buffer as a source of vertices.
