### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by bvssvni** [glium/glium#1599]
There was some breaking changes in glutin, so I could not figure out how to update.

[Eco](https://github.com/pistondevelopers/eco) suggests the following updates:

```
"glium": {
    "order": 3,
    "bump": {
      "old": "0.16.0",
      "new": "0.17.0"
    },
    "dependencies": {
      "glutin": {
        "bump": {
          "old": "0.7.1",
          "new": "0.8.1"
        }
      }
    },
    "dev-dependencies": {
      "image": {
        "bump": {
          "old": "0.12.0",
          "new": "0.14.0"
        }
      }
    }
  },
```

**Comment by sharazam** [comment]
See https://github.com/tomaka/glutin/pull/897

Big change in glutin, moves more to winit. This is a breaking change, because the will be no `.poll_events()` and `.wait_events()` anymore.

**Comment by est31** [comment]
I think this issue isn't relevant any more.
