### ISSUE TITLE
Screen goes from -1.0 to 0.5 in x and y.

### ISSUE THREAD

**Issue by vadixidav** [glium/glium#1606]
I see this with the teapot demo:

![image](https://user-images.githubusercontent.com/12789579/28508747-fd298aa4-700a-11e7-84c9-3f06c732adbd.png)

It shows up in programs I make as well. Origin is where the teapot is, which is 0, 0. It should be in the center.

The actual display seems to go from -1.0 to 0.5 in X and Y.

I am on Arch Linux. My friend reports this does not happen on windows. This regression was introduced from  #1601.

**Comment by mitchmindtree** [comment]
I am also on Arch Linux (Gnome running X11) but do not get this behaviour.

This is what I see when I do `cargo run --example teapot`

![screenshot from 2017-07-24 16-04-28](https://user-images.githubusercontent.com/4587373/28510141-f1160aa6-7089-11e7-8cae-aa9ce28e04e1.png)

Are you running Wayland or X11?  Does the same bug happen for you when running the glutin or winit examples?

**Comment by vadixidav** [comment]
It happens for all the examples. I am using i3 and xorg with intel
graphics. I can check on other computers to see if I get the same behavior.
I will also get the graphics version and more screenshots and put them here.

**Comment by vadixidav** [comment]
I can confirm that it looks fine on Windows 10 with a GTX 1070.

![image](https://user-images.githubusercontent.com/12789579/28555477-37305002-70ce-11e7-829f-b63741334a7f.png)

**Comment by vadixidav** [comment]
On Arch Linux (i3 on Xorg) with a GTX 1070 with official nvidia drivers I am also getting the correct image.

![image](https://user-images.githubusercontent.com/12789579/28555804-30d5a5d4-70d0-11e7-854d-026198c81908.png)

**Comment by vadixidav** [comment]
Okay, I double checked and the issue still persists on my laptop. This is the original machine the issue occurs on.

The laptop's processor is `i7-5500U`. It has `Intel HD Graphics 5500` as its graphics. My Mesa version is `17.1.4-1`.

**Comment by vadixidav** [comment]
Also just updated to Mesa `17.1.5-1` and I have kernel `4.11.9-1` on the laptop with the issue.

**Comment by mitchmindtree** [comment]
Do you have any custom DPI scaling or anything on your laptop? Can you check that the [`winit::Window::hidpi_factor`](https://docs.rs/winit/0.7.5/winit/struct.Window.html#method.hidpi_factor) method returns the correct scaling factor? It would also be interesting to see what [get_inner_size_pixels](https://docs.rs/winit/0.7.5/winit/struct.Window.html#method.get_inner_size_pixels) and [get_inner_size_points](https://docs.rs/winit/0.7.5/winit/struct.Window.html#method.get_inner_size_points) return.

> This regression was introduced from #1601.

Unfortunately quite a lot of upstream changes were introduced at once in #1601. I imagine that, if anywhere, the problem likely stems from a change in winit as that is where the windowing, dpi and events are handled. There is some [discussion of DPI issues here](https://github.com/tomaka/winit/issues/169) - maybe this relates to your problem?

**Comment by vadixidav** [comment]
@mitchmindtree That might be related to the problem. The laptop's display is `2560 x 1700` (it's a Chromebook Pixel 2015). The DPI is the default for Xorg, which might be 90. I will check later when I have time to double check that info on the laptop and ill start investigating whats going on there on the winit side (if the bug goes down into their code).

**Comment by avl** [comment]
I'm also seeing this. on Ubuntu 17.04 with xfce. It seems like some sort of DPI scaling bug. The mouse cursor changes size when hovering over the glium window, which I think may be some kind of DPI scaling thing.

**Comment by wkunkel** [comment]
I'm also experiencing this problem. It doesn't happen with the glutin examples, however, which leads me to believe that it's a problem at this level, not down in winit.

**Comment by wkunkel** [comment]
I'm also experiencing this problem. It doesn't happen with the glutin examples, however, which leads me to believe that it's a problem at this level, not in winit. I have my `DisplaySize` set in xorg.conf, so `xdpyinfo` returns
```
screen #0:
  dimensions:    2880x1620 pixels (381x214 millimeters)
  resolution:    192x192 dots per inch
```
Removing the `DisplaySize` setting makes the problem disappear, but X11 then detects my DPI as `96x96` and everything is too small. The fact that `xdpyinfo` reports the correct DPI when my `DisplaySize` is set makes me believe that this issue is unrelated to https://github.com/tomaka/winit/issues/169

**Comment by wkunkel** [comment]
Adding some debug info, I get
```
HiDPI Factor: 2
Inner Size (px): Some((2048, 1536))
Inner Size (pt): Some((1024, 768))
```
The HiDPI factor seems right, but the inner size in pixels seems much too large: the window doesn't even cover a quarter of my screen. Maybe the size in points is the actual size in pixels?

**Comment by wkunkel** [comment]
It looks like this issue was fixed by https://github.com/tomaka/winit/pull/245/commits/d65d9950f27d7511d2dc62999fcf0733a0fda416 Testing glium with a modified glutin which pulls winit from Github no longer shows this problem.

**Comment by avl** [comment]
I can confirm that upgrading winit solves this on my system as well. Maybe we can close this bug?

**Comment by vadixidav** [comment]
I actually don't have the original laptop anymore, but I believe this is sufficient evidence to close it.
