### ISSUE TITLE
Uploading monochrome textures?

### ISSUE THREAD

**Issue by sharazam** [glium/glium#1610]
A question - what would be the way to upload monochrome textures (from a font atlas)? `GL_LUMINANCE` was depreceated in favor of `GL_RED` / `GL_RG` - ok, but how do I set `GL_RED` on a new texture (using glium)?

**Comment by tomaka** [comment]
Any texture data with only one component is equivalent to `GL_RED`.

**Comment by sharazam** [comment]
Alright, I was just wondering if you have to set it explicitly in order to get a greyscale image with the same color for each component.

Is there any way to do this when binding a texture (without doing the following in the fragment shader):

```glsl
    vec4 cur_color = texture(tex, v_tex_coords);
    cur_color.g = cur_color.r;
    cur_color.b = cur_color.r;
```

If I just output `texture(tex, v_tex_coords)` to the screen, the contents will be colored red. I'm not that experienced in OpenGL, but if `GL_RED` is already set, shouldn't this give me a greyscale texture?

**Comment by tomaka** [comment]
There's no concept of "greyscale" anymore in OpenGL.

Textures have between one and four components. Most of the time people use the four components for red, green, blue and alpha, but that distinction is only in the programmer's mind.

In other words the code you pasted is correct.
