### ISSUE TITLE
MultiOutputFrameBuffer and gl_FragData[*]

### ISSUE THREAD

**Issue by NiklasRosenstein** [glium/glium#1611]
I create a MultiOutputFrameBuffer as

```rust
  let output = [ ("matte", &diffuse_texture), ("distanceField", &distance_texture) ];
  let mut fbo = glium::framebuffer::MultiOutputFrameBuffer::new(&display, output.iter().cloned()).unwrap();
```

Now when I try to draw using my shader

```rust
    let compute_uniform = uniform! {
      px: 1.0 / image_dimensions.0 as f32,
      py: 1.0 / image_dimensions.1 as f32,
      matte: &diffuse_texture,
      distanceField: &distance_texture
    };
    fbo.draw(&vertex_buffer, &index_buffer, &compute_program,
             &compute_uniform, &Default::default()).unwrap();
```

I get the following runtime error:

```
thread 'main' panicked at 'The fragment output `matte` was not found in the program', C:\Users\niklas\.cargo\registry\src\github
.com-1ecc6299db9ec823\glium-0.17.0\src\framebuffer\mod.rs:521
```

My assumption is that the program is missing an `out vec4 matte;` (and then probably also `out vec4 distanceField`). However, I would very much like to not modify the shader as I already have a working version with it in Python.

Is there a way to use the MultiOutputFrameBuffer and have the shader write to `gl_FragData[*]` instead of such named outputs?

My shader currently looks a bit like this and is used to mutate the `matte` and `distanceField` texture over time.

```glsl
#version 110

uniform sampler2D matte;
uniform sampler2D distanceField;
uniform float px;
uniform float py;
varying vec2 v_texcoord;

void main() {
  float some_weight = ...;
  gl_FragData[0] = texture2D(matte, v_texcoord) * some_weight;
  gl_FragData[1] = texture2D(distanceField, v_texcoord) * some_weight;
}
```

And the program is created with

```rust
  let compute_program = program!(&display,
    110 => {
      vertex: src_compute_vert,
      fragment: src_compute_frag
    }
  ).unwrap();
```

**Comment by tomaka** [comment]
> Is there a way to use the MultiOutputFrameBuffer and have the shader write to gl_FragData[*] instead of such named outputs?

No, that's not possible. `gl_FragData` has been deprecated and removed and glium doesn't support it.

**Comment by NiklasRosenstein** [comment]
I see. Turns out updating the shader code is not too complicated. I was just hoping I wouldn't need to duplicate the shader code or update the Python code. :) Thanks!

**Comment by NiklasRosenstein** [comment]
One more question, if I may? When I use the MultiOutputFrameBuffer with the `matte` and `distanceField` textures, is it safe to sample from these textures and write to them at the same time? a la

```rust
    let output = [ ("matteOut", &diffuse), ("distanceOut", &distance) ];
    let mut fbo = glium::framebuffer::MultiOutputFrameBuffer::new(
      &display, output.iter().cloned()).unwrap();

    if loop_index > 0 {
      // Next computational step.
      let compute_uniform = uniform! {
        px: 1.0 / image_dimensions.0 as f32,
        py: 1.0 / image_dimensions.1 as f32,
        matte: &diffuse,                          // < same source as target texture
        distanceField: &distance                  // < same source as target texture
      };
      fbo.draw(&vertex_buffer, &index_buffer, &compute_program,
              &compute_uniform, &Default::default()).unwrap();
    }
```

Or do I have to use the ping-pong technique?

**Comment by tomaka** [comment]
Yeah you're supposed to ping-pong. It may work on some implementations but not on others.

**Comment by NiklasRosenstein** [comment]
Ok I've got the results I wanted without using the ping-pong method.

**Comment by NiklasRosenstein** [comment]
Oh, I didn't see your comment.

> It may work on some implementations but not on others.

Good to know, thank you!
