### ISSUE TITLE
clippy reports warning in implement_vertex!

### ISSUE THREAD

**Issue by chyvonomys** [glium/glium#1620]
This code:
```
#[macro_use]
extern crate glium;

#[derive(Clone, Copy)]
struct MyVtx {
    pos: [f32; 3],
}

implement_vertex!(MyVtx, pos);

fn main() {
}
```

when analyzed with `clippy` reports this warning:
```
warning: calls to `std::mem::forget` with a value that implements Copy. Forgetting a copy leaves the original intact.
 --> src/main.rs:9:1
  |
9 | implement_vertex!(MyVtx, pos);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(forget_copy)] on by default
note: argument has type MyVtx
 --> src/main.rs:9:1
  |
9 | implement_vertex!(MyVtx, pos);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  = help: for further information visit https://github.com/rust-lang-nursery/rust-clippy/wiki#forget_copy
  = note: this error originates in a macro outside of the current crate
```

**Comment by tomaka** [comment]
Err, I wonder how you're supposed to implement `offsetof` then.

**Comment by chyvonomys** [comment]
What do you think about this workaround (without creating a dummy zeroed object): https://github.com/rust-lang/rfcs/issues/710#issuecomment-321464903

**Comment by tomaka** [comment]
That was the former solution before it was changed a few days/weeks ago. It was changed because it was causing segfaults.

**Comment by chyvonomys** [comment]
Correct me if I am wrong: `implement_vertex!` requires struct to have `Copy` trait. That means that struct can not have `Drop` trait. That means `mem::forget` can be simply ommited in this case because all it does is "drops value without calling its destructor". But there is no desctructor so just end of scope is fine.

Btw, in which case it segfaulted previously? Does it have to be some special struct?

**Comment by tomaka** [comment]
`implement_vertex!` does not require `Copy` right now, but I guess we could change it so that it's the case.

> Btw, in which case it segfaulted previously? Does it have to be some special struct?

Creating a null pointer and grabbing the memory address of the field caused a segfault. I don't think it's relevant to the kind of struct.

**Comment by chyvonomys** [comment]
Well, `glium::Vertex` does require:
```
error[E0277]: the trait bound `Vtx: std::marker::Copy` is not satisfied
 --> src\main.rs:8:1
  |
8 | implement_vertex!(Vtx, pos);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `Vtx`
  |
  = note: required by `glium::Vertex`
```

**Comment by tomaka** [comment]
Oh, so I guess removing the `forget` is fine (as long as it's explained in a comment).
