### ISSUE TITLE
Better or manual selection of renderer for headless contexts

### ISSUE THREAD

**Issue by ashkitten** [glium/glium#1626]
Under Linux, the renderer selection is incorrect when creating a headless context. When I create a context for a `Display`, the opengl version string is `"4.5.0 NVIDIA 387.12"`, but when I create one for a `Headless`, the version string reads `"3.0 Mesa 17.2.2"`.

This behavior isn't necessarily a bug, as I assume it stems from the headless context builder not using X to create the context, but either way we need a way to specify an alternate renderer for the context.

**Comment by tomaka** [comment]
This is most likely a bug in glutin.

**Comment by ashkitten** [comment]
Ah okay, shall I make a bug there and close this?

**Comment by tomaka** [comment]
Yes please.
