### ISSUE TITLE
Question: Any Reason why AsUniformValue  wasn't implemented as From<T>?

### ISSUE THREAD

**Issue by JustinRyanH** [glium/glium#1629]
I was digging through the Uniform code and I noticed that we use` AsUniformValue` for type conversions. I'm curious if there is a reason glium went with that instead of implementing a bunch of `From<T>` . Would there be any resistance to adding `From<T>` equivalents to the UniformValue enum? I don't think we'd need to deprecate the existing usage.

**Comment by mitchmindtree** [comment]
I imagine that the implementation is currently this way as this code pre-dates the addition of `From` and `Into` in the std, though I could be wrong!

One difference to note is that the `AsUniformValue` conversion method  takes `&self` rather than `self`, but I suppose we could get around this by implementing `From` for references to the types instead, e.g. `From<&'a T>`? Would be nice to hear @tomaka's thoughts briefly before going ahead with this in case there is some special case we're missing.

**Comment by tomaka** [comment]
> I imagine that the implementation is currently this way as this code pre-dates the addition of From and Into in the std, though I could be wrong!

Yes, I think that's the case if I remember correctly.

I think `From` is strictly superior to `AsUniformValue`.

**Comment by JustinRyanH** [comment]
thanks for the response. I'll get together a pull request

**Comment by tomaka** [comment]
Don't both with implementing `From` for `&'a T`. The fact that `AsUniformValue` takes a `&self` instead of a `self` is also a mistake I think.

**Comment by JustinRyanH** [comment]
@tomaka  @mitchmindtree  I've started a pull request to handle the current issue, however I would love to have feedback. I've made an small change to the AsUniformValue api, but I think by the time this PR is ready to merge into master that can hopefully the fixed. https://github.com/JustinRyanH/glium/pull/2

**Comment by tomaka** [comment]
You should make `as_uniform_value()` takes a `self` instead of a `&self`. Don't bother with borrowing. It will make things much simpler as well.

**Comment by JustinRyanH** [comment]
dropping the `&'a self` and `&self` reference is causing a lot of the pain with `Fence` and `Alloc` for buffer. I think I could refactor those into a state that would allow me to do that, but I have some questions on the intent of their structure.  

I've noticed `Buffer<T>` has Drop, so it makes it rough to with moving it's values into other objects. I'm curious if we should instead implement a Tuple struct of (`Alloc`, `Fence`) that is passed around as a `std::rc::Rc ` between Buffers and that can handle the cleanup of those two when there are no buffers referencing that combination.

**Comment by tomaka** [comment]
Well, a `BufferSlice<'a>` is already more or less a `&'a Buffer`. At least that's what it exposes. Not sure I understand the issue.
If you're trying to implement `AsUniformValue` for `Buffer`, maybe you should implement it for `&'a Buffer` instead.

**Comment by JustinRyanH** [comment]
Oh yeah I should be more clear. 

I usually run into a stopgap from here, 
``` rust
impl<'a, T: ?Sized> AsUniformValue<'a> for UniformBuffer<T> where T: UniformBlock + Content {
    #[inline]
    fn as_uniform_value(&'a self) -> UniformValue {
        #[inline]
        fn f<T: ?Sized>(block: &program::UniformBlock)
                        -> Result<(), LayoutMismatchError> where T: UniformBlock + Content
        {
            // TODO: more checks?
            T::matches(&block.layout, 0)
        }

        UniformValue::Block(self.buffer.as_slice_any(), f::<T>)
    }
}
```

However, when . I replace the `'&'a self` with a `self` I run into some lifetime issues.
``` bash
error[E0597]: `self.buffer` does not live long enough
   --> src/uniforms/buffer.rs:244:29
    |
244 |         UniformValue::Block(self.buffer.as_slice_any(), f::<T>)
    |                             ^^^^^^^^^^^ does not live long enough
245 |     }
    |     - borrowed value only lives until here
    |
note: borrowed value must be valid for the lifetime 'a as defined on the impl at 233:1...
   --> src/uniforms/buffer.rs:233:1
    |
233 | / impl<'a, T: 'a + ?Sized> AsUniformValue<'a> for UniformBuffer<T> where T: UniformBlock + Content {
234 | |     #[inline]
235 | |     fn as_uniform_value(self) -> UniformValue<'a> {
236 | |         #[inline]
...   |
245 | |     }
246 | | }
    | |_^

error[E0507]: cannot move out of borrowed content
  --> src/uniforms/uniforms.rs:52:27
   |
52 |         output(self.name, self.value.as_uniform_value());
   |                           ^^^^^^^^^^ cannot move out of borrowed content
```

I think the lifetime guarantees get lost when we use the move `self`.  We would get a more  ergonomics code if the various `BufferSlice*` types if they had a reference of some sort to Buffer<T> or even a Tuple of Buffer<T>'s  `(Alloc, Fences)`. Does that make sense?

**Comment by tomaka** [comment]
In theory, you should be able to do this:

```rust
impl<'a, T: ?Sized> AsUniformValue<'a> for &'a UniformBuffer<T>
```
