### ISSUE TITLE
Question: Having shared ownership of Display

### ISSUE THREAD

**Issue by nausicaea** [glium/glium#1636]
In my current project, I have two structs (`Renderer` and `UserInterface`) that both need read access to `glium::backend::glutin::Display`. I was hoping to solve this by wrapping `Display` in `std::rc:Rc`, but then that strategy has issues with other parts of the `glium` API, such as `glium::VertexBuffer`, which requires a generic type with trait bound `glium::backend::Facade` as the first argument to `glium::VertexBuffer::new`.

The following line, causes the subsequent compilation error:

    let vertex_buffer = glium::VertexBuffer::new(&renderer.display, &e_data).expect("...");

    the trait bound `std::rc::Rc<glium::Display>: glium::backend::Facade` is not satisfied

Is there a way around this issue? I'm relatively new to Rust, and some concepts are still very difficult for me to understand. I appreciate your help!

**Comment by tomaka** [comment]
Hi. You can simply clone the display itself, as it already contains an Rc underneath.

**Comment by nausicaea** [comment]
Ha! I knew it was somehow as simple as that. Thanks!
