### ISSUE TITLE
gl function was not loaded

### ISSUE THREAD

**Issue by Remco47** [glium/glium#1648]
I get this error with my glium-based project, so I went back to the triangle example, and the same happens here. The error only happens when compiled in release mode. Debug mode works fine.

glium version: master 014697825625d5238fdc783b77016260d418dc54
rustc version: rustc 1.24.0-nightly (0a2e9ade8 2017-11-29)

> Remco@remcolaptop-windows ~/Projects/glium (master)$ RUST_BACKTRACE=1 cargo run
 --release --example triangle
    Finished release [optimized] target(s) in 0.0 secs
     Running `target\release\examples\triangle.exe`
thread 'main' panicked at 'gl function was not loaded', C:\Users\Remco\Projects\glium\target\release\build\glium-636932af38e2a487\out/gl_bindings.rs:2535:12
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:383
   3: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   5: _rust_alloc_zeroed
   6: <glium::sync::SyncNotSupportedError as core::fmt::Debug>::fmt
   7: glium::version::get_gl_version
   8: glium::backend::glutin::Display::new
   9: glium::backend::glutin::Display::new
  10: POW10
  11: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  12: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:50
  13: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  14: BaseThreadInitThunk
error: process didn't exit successfully: `target\release\examples\triangle.exe` (exit code: 101)

**Comment by rennis250** [comment]
Experiencing the same. I'll try downgrading rust for now. thanks.

**Comment by mitchmindtree** [comment]
I'm also running into this on nightly (linux). Anyone have a link to a related rust-lang/rust issue?

**Comment by mchesser** [comment]
I believe this is caused by this issue: https://github.com/brendanzab/gl-rs/issues/438 -- the newest version of glutin works fine, however glium is using an old version.

**Comment by virtualritz** [comment]
I'm seeing this on macOS 10.15.4 on a 2014 MBP with Intel Iris GPU.
