### ISSUE TITLE
Offset rendering on Linux since glutin upgrade

### ISSUE THREAD

**Issue by FauxFaux** [glium/glium#1657]
Since 5de27b021f13d4eeed8bab43eefcbee0786cf7dd ("update glutin and gl_generator"), on Ubuntu Artful (16.10) with `nvidia-384`, things render off-centre. Here's the `cargo run --example image`:

![image](https://user-images.githubusercontent.com/328180/34652929-cb069476-f3dc-11e7-8c10-c8be22fd210f.png)

Here's what it should look like. Same machine, but glium at commit 63577da7987923bf8829b826a6c94f7fdff2be61, before the updates. Note the (r) to the right of the L, and the even margin:

![image](https://user-images.githubusercontent.com/328180/34652956-0fb3dbce-f3dd-11e7-80e1-43ff0d4b5ee8.png)

It's nothing to do with the window size, it happens at all sizes; the discrepancies in the above screenshots are my laziness.

Not super visually significant in this example, but presumably related to https://github.com/PistonDevelopers/conrod/issues/1120 which is awful.

I am still unable to find a pure glutin example that shows the same behaviour.

**Comment by tomaka** [comment]
Probably a HiDPI issue, as always.

**Comment by FauxFaux** [comment]
I have large monitors (2 * 2560x1440), but they're not HiDPI by the normal standards, nor do I have any scaling config as far as I can remember. Issue happens in Gnome and in i3, which should use different scaling settings.

```
% xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    5120x1440 pixels (1204x342 millimeters)
  resolution:    108x107 dots per inch
```

**Comment by spearman** [comment]
Reverting the change to the X11 window `get_inner_size` method made in (https://github.com/tomaka/winit/commit/48902297b7bd02fc20f3ae7012074c6b93674980) seems to fix it:

https://github.com/spearman/winit/commit/d3cc220f3ec42feecb3e123e81df96481367e90c

Not sure if that's the real problem or if the change was intentional and the problem is elsewhere.

**Comment by tomaka** [comment]
Hmm, maybe glium applies the HiDPI stuff on top of glutin.

**Comment by daboross** [comment]
I've been trying to replicate this on my computer running Ubuntu 16.10, but I haven't found any setting which makes DPI reported by xdpyinfo anything other than 96x96. Was there some setting you had to change to get it to 108x107 that I could also change?

**Comment by daboross** [comment]
Ah cool! I can also reproduce this now with `xrandr --dpi 200` on Xorg.

**Comment by daboross** [comment]
Alright, thanks!! I think I've found the culprit in glium: it accounts for `get_inner_size()` returning dpi-scaled points, while the commit in `winit` mentioned earlier changes it to return absolute pixels. (code at https://github.com/glium/glium/blob/master/src/backend/glutin/mod.rs#L265).

This was much easier to find with the [commit](https://github.com/tomaka/winit/commit/48902297b7bd02fc20f3ae7012074c6b93674980) @spearman and the isolation of the issue to the winit upgrade and dpi scaling you found, @FauxFaux.
