### ISSUE TITLE
HiDPI broken on OS X by #1663

### ISSUE THREAD

**Issue by ebarnard** [glium/glium#1673]
Since #1663 `Frame::get_dimensions` returns the size of the window in dpi scaled pixels not raw pixels causing rendering errors.

I think this is a bug with `winit`'s zWindow::inner_size_pixelsz returning the number of points not pixels on OS X but I just want to confirm that the expected behaviour of `Frame::get_dimensions` is to return the size in raw pixels.

Issue example:
<img width="1140" alt="screen shot 2018-02-08 at 01 31 53" src="https://user-images.githubusercontent.com/1059683/35950766-f8f9ba42-0c6f-11e8-898a-a3bb9fb5e45a.png">

**Comment by chrisbenincasa** [comment]
I'm experiencing the same issue. Reverting to v0.19.0 (1 prior to the linked patch) fixed the issue for me, so it does seem related to #1663 .

**Comment by ebarnard** [comment]
Appears to be and be solved by tomaka/winit#359.
