### ISSUE TITLE
How to draw on a CompressedSrgbTexture2d?

### ISSUE THREAD

**Issue by fschutt** [glium/glium#1688]
Let's say I have a `CompressedSrgbTexture2d`:

```rust
let mut target = CompressedSrgbTexture2d::empty_with_format(
    display,
    CompressedSrgbFormat::Bptc,
    CompressedMipmapsOption::NoMipmap,
    max_width,
    max_height).unwrap();
```

How can I use `draw()` on it? Usually, with `Texture2d`, I'm able to do:

```rust
texture.as_surface().draw(/*  */).unwrap()
```

However, for `SrgbTexture2d` and `CompressedSrgbTexture2d` such a mechanism doesn't seem to exist - I don't know how to get from a `CompressedSrgbTexture2d` to a `.draw()` call. For now I'm simply using `Texture2d` instead, but this isn't really optimal.

**Comment by tomaka** [comment]
You cannot draw on a compressed texture, this is one of the inherent drawbacks to using them.
