### ISSUE TITLE
MultiOutputFrameBuffer has incorrect documentation

### ISSUE THREAD

**Issue by vadixidav** [glium/glium#1719]
In the docs for the `glium::framebuffer::MultiOutputFrameBuffer` struct, it states: "This struct is useless for the moment". This made me think it wasn't possible to use it, but I noticed it was used in the `deferred` example. This documentation should be replaced with something more correct.

**Comment by vadixidav** [comment]
Also, I have very extensively used the `MultiOutputFrameBuffer` at this point, and I can say it is definitely useful and works.

**Comment by Boscop** [comment]
Thanks for letting me know. I was also discouraged by the doc, but now I will start using it.

**Comment by est31** [comment]
PRs welcome!
