### ISSUE TITLE
events loop 2 alpha release?

### ISSUE THREAD

**Issue by Lokathor** [glium/glium#1756]
Can there be an alpha release of glium that bumps the glutin version to its alpha version, which in turn uses the winit 0.20-alpha version?

**Comment by est31** [comment]
Sure, PRs are welcome!

**Comment by Lokathor** [comment]
A simplistic attempt to bump the version leads to the following build error:

```
D:\dev\glium>cargo test
    Updating crates.io index
error: failed to select a version for `glutin`.
    ... required by package `glium v0.25.1-alpha1 (D:\dev\glium)`
versions that meet the requirements `^0.22.0-alpha1` are: 0.22.0-alpha1

the package `glium` depends on `glutin`, with features: `icon_loading` but `glutin` does not have these features.


failed to select a version for `glutin` which could resolve this conflict
```

[It seems](https://github.com/rust-windowing/glutin/blob/master/glutin/Cargo.toml) that one of the features that you're depending on has gone away. You'll have to decide how to handle that. Above my pay grade for a basic PR I'm afraid ;_;

**Comment by est31** [comment]
For reference discussion about this is in https://github.com/rust-windowing/winit/pull/799

I think you can just remove the `icon_loading` feature. While it's definitely non-trivial to upgrade glutin because it has some larger changes, help would very much be appreciated!

**Comment by Lokathor** [comment]
The [glutin alpha release](https://crates.io/crates/glutin/0.22.0-alpha1) is already out and using the new winit 0.20 alpha, so if `glium` can just drop that feature then that simplifies things I think.

I ended up going ahead and starting on a `gfx-hal` based project, so I think it's unlikely that I'll put in the PR for `glium` to be pushed forward, but we can leave this open for others to find.

**Comment by KeyMaster-** [comment]
I started using glium recently and actually did this upgrade for the winit changes. See my fork (https://github.com/KeyMaster-/glium) for that, I only made the absolutely minimal changes to get it working, but not much was needed (see [here](https://github.com/KeyMaster-/glium/commit/7241d675fc290413f2e8b299e0b453a1a32c3622)).
I could PR this if it'd be something worth building on.

**Comment by Lokathor** [comment]
that sounds great to contribute!

**Comment by est31** [comment]
@KeyMaster- wow, that's nice! Feel free to file a PR. You should probably call the version `"0.25.0-alpha1"` but otherwise it looks great.

**Comment by KeyMaster-** [comment]
Just submitted the PR, see #1757. I also pulled in the 0.25.1 changes.

**Comment by est31** [comment]
It's released: https://crates.io/crates/glium/0.26.0-alpha1

Some examples are broken, which is a blocker for the 0.26.0 release: #1758
