### ISSUE TITLE
Improve picking example by adding world position output. Also fix overflow bug.

### ISSUE THREAD

**Issue by nick-parker** [glium/glium#1762]
I'm trying to extend the picking example to output the world position of the pick target. My plan is to read from the depth buffer and then unproject using that value. I replaced the DepthRenderBuffer with a DepthTexture2D and nothing broke, but I can't read the relevant pixel's depth into a PixelBuffer. See the error trace below.

Do you have any tips on accessing depth values like this?

Also, I fixed the subtract with overflow bug in the generation of the Rect target. At least on Ubuntu, If a Glutin window initializes with its bottom border above the mouse, if you move the mouse while it has focus (eg, right after it opens) it'll emit a CursorMoved with a y coordinate greater than the height of the window. So if you try to subtract those two as u32s there'll obviously be trouble. My fix is a little bit clunky to keep it as a one liner, but it does fix it.

Debug message with high or medium severity: `GL_INVALID_FRAMEBUFFER_OPERATION error generated. Operation is not valid because a bound framebuffer is not framebuffer complete.`.
Please report this error: https://github.com/tomaka/glium/issues
Backtrace:
   1 - 0x56133bcd1d87
         _ZN9backtrace9backtrace9libunwind5trace17hd6c7279f3d7d3401E at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/src/backtrace/libunwind.rs:88
         _ZN9backtrace9backtrace20trace_unsynchronized17h04f554d3c3916f8bE at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/src/backtrace/mod.rs:66
   2 - 0x56133bcd1df8
         _ZN9backtrace9backtrace5trace17hb55e09589e55f03eE at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.33/src/backtrace/mod.rs:53
   3 - 0x56133bc52825
         _ZN5glium7context22default_debug_callback17hbd011241c98ae48eE at src/context/mod.rs:852
   4 - 0x56133baae4c5
         _ZN4core3ops8function5FnMut8call_mut17hd79a135f57232096E at /rustc/dfd52ba6ac2262c6b61c59ec86bfd23e4e53d3de/src/libcore/ops/function.rs:148
   5 - 0x56133bc38887
         _ZN82_$LT$alloc..boxed..Box$LT$F$GT$$u20$as$u20$core..ops..function..FnMut$LT$A$GT$$GT$8call_mut17h5ad77de397372ec7E at /rustc/dfd52ba6ac2262c6b61c59ec86bfd23e4e53d3de/src/liballoc/boxed.rs:773
   6 - 0x56133bc535ac
         _ZN5glium7context19init_debug_callback16callback_wrapper17hd729e920905a934fE at src/context/mod.rs:939
   7 - 0x7fad7a6f2ce8
         <unknown> at <unknown>:??
   8 - 0x7fad7a6f2e30
         <unknown> at <unknown>:??
   9 - 0x7fad7a6f30f2
         <unknown> at <unknown>:??
  10 - 0x7fad7a677c6a
         <unknown> at <unknown>:??
  11 - 0x56133ba82fd8
         _ZN5glium2gl2Gl10ReadPixels17h8a0a1f51a882fa2dE at /home/nick/rust/glium/target/debug/build/glium-0d41d2e420f7bf3b/out/gl_bindings.rs:8032
  12 - 0x56133bb7ea3c
         _ZN5glium3ops4read4read17h9da08972f5b6e3dcE at /home/nick/rust/glium/src/ops/read.rs:251
  13 - 0x56133baef2ae
         _ZN5glium7texture3any15TextureAnyImage24raw_read_to_pixel_buffer17h6a4887bee1444208E at /home/nick/rust/glium/src/texture/any.rs:1467
  14 - 0x56133ba9b22c
         _ZN7picking4main28_$u7b$$u7b$closure$u7d$$u7d$17h6d9ac9a8601e42cbE at examples/picking.rs:236
  15 - 0x56133bb7adaf
         _ZN7picking7support10start_loop28_$u7b$$u7b$closure$u7d$$u7d$17h02a9ae245c1aa7e1E at examples/support/mod.rs:39
  16 - 0x56133ba72db5
         _ZN5winit13platform_impl8platform3x1118EventLoop$LT$T$GT$10run_return17hde5062b3c78c1b82E at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha2/src/platform_impl/linux/x11/mod.rs:344
  17 - 0x56133ba7342a
         _ZN5winit13platform_impl8platform3x1118EventLoop$LT$T$GT$3run17h55a2b96033b63a64E at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha2/src/platform_impl/linux/x11/mod.rs:370
  18 - 0x56133ba9ca49
         _ZN5winit13platform_impl8platform18EventLoop$LT$T$GT$3run17h96b7e78e4453412bE at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha2/src/platform_impl/linux/mod.rs:545
  19 - 0x56133babbd63
         _ZN5winit10event_loop18EventLoop$LT$T$GT$3run17h1bbbc5bed2be0a43E at /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha2/src/event_loop.rs:139
  20 - 0x56133bb7abc7
         _ZN7picking7support10start_loop17hdfd955e0263835c3E at examples/support/mod.rs:22
  21 - 0x56133bb8d526
         _ZN7picking4main17h18a457e48e3a338cE at examples/picking.rs:126
  22 - 0x56133ba739b0
         _ZN3std2rt10lang_start28_$u7b$$u7b$closure$u7d$$u7d$17h05081317df58decaE at /rustc/dfd52ba6ac2262c6b61c59ec86bfd23e4e53d3de/src/libstd/rt.rs:64
  23 - 0x56133c11aa73
         _ZN3std2rt19lang_start_internal28_$u7b$$u7b$closure$u7d$$u7d$17h070cb399cf0a0557E at src/libstd/rt.rs:49
         _ZN3std9panicking3try7do_call17h428b0adfc5219f62E at src/libstd/panicking.rs:296
  24 - 0x56133c11e82a
         __rust_maybe_catch_panic at src/libpanic_unwind/lib.rs:82
  25 - 0x56133c11b57d
         _ZN3std9panicking3try17hba4d291c5c240caeE at src/libstd/panicking.rs:275
         _ZN3std5panic12catch_unwind17h34d913ddb8b92fc2E at src/libstd/panic.rs:394
         _ZN3std2rt19lang_start_internal17h8364b9bdca2d4910E at src/libstd/rt.rs:48
  26 - 0x56133ba73989
         _ZN3std2rt10lang_start17h3f1fe8ac3f3aff80E at /rustc/dfd52ba6ac2262c6b61c59ec86bfd23e4e53d3de/src/libstd/rt.rs:64
  27 - 0x56133bb8dc5a
         main at <unknown>:??
  28 - 0x7fad7ef79b97
         __libc_start_main at <unknown>:??
  29 - 0x56133ba66e1a
         _start at <unknown>:??
  30 - 0x0
         <unknown> at <unknown>:??

**Comment by nick-parker** [comment]
Oops, forgot to link my code: https://github.com/nick-parker/glium/blob/master/examples/picking.rs

**Comment by nick-parker** [comment]
Nevermind, I solved this by changing the PixelBuffer used for UIDs to F32F32 format, making the UIDs floats, and then copying the depth information into the second channel of the UID buffer in my shader.

I've got world coordinate output in my main project, but I'm using nalgebra for the transforms so it'd be a bit of work to port back into the example without that dependency.

**Comment by est31** [comment]
Thanks for bringing attention to the overflow bug! #1763

For my own personal project, I'm interested in reading the depth buffer myself, so thanks for the suggestions. I'm closing this as there is nothing left to do for glium.
