### ISSUE TITLE
Sampler CLAMP_TO_BORDER is not supported

### ISSUE THREAD

**Issue by unknownue** [glium/glium#1772]
```
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
````
It seems there is no equivalent replacement for the code above for the texture sampler.

**Comment by unknownue** [comment]
Related PR #1701

**Comment by est31** [comment]
@unknownue does that PR work for you? If so, I'll merge it.

**Comment by unknownue** [comment]
Yes, I try this PR and it does work for me. Hope to merge it.

**Comment by est31** [comment]
#1701 is merged
