### ISSUE TITLE
Update to glutin-0.22.0-alpha3

### ISSUE THREAD

**Issue by Lokathor** [glium/glium#1773]
As of a few hours ago some more `glutin` code got pushed which brings `glutin` up to version 0.22.0-alpha3, so naturally `glium` should release another alpha as well.

I do not _think_ that there are major changes, so it should be an easy migration.

**Comment by est31** [comment]
PRs welcome!

**Comment by est31** [comment]
See #1774

**Comment by est31** [comment]
Alpha 3 crates.io release is uploaded: https://crates.io/crates/glium/0.26.0-alpha3
