### ISSUE TITLE
CompilationError("0:2(10): error: GLSL 1.40 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES\n")'

### ISSUE THREAD

**Issue by bendeg** [glium/glium#1783]
I'm following tutorials and Tutorial 02 failed (triangle). Tutorial 01 worked fine.

**thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("0:2(10): error: GLSL 1.40 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES\n")', src/libcore/result.rs:999:5**

Looking at glxinfo, I think my system (old laptop Lenovo T61, Linux Debian 32bits) doesn't support recent versions.
I tried to upgrade with mesa-utils but it's stuck there.

<pre>$ glxinfo | grep -i opengl
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) 965GM x86/MMX/SSE2
OpenGL version string: 2.1 Mesa 19.1.4
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 19.1.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
</pre>

But I found shaders for version 120 in the crate shaders_graphics2d
[http://coredump-ch.github.io/rpsrtsrs/shaders_graphics2d/colored/constant.VERTEX_GLSL_120.html](url)

I changed those shaders to make the Tutorial 02 work

<pre>let vertex_shader_src = r#"
    #version 120
    attribute vec2 position;
    void main() {
    gl_Position = vec4(position, 0.0, 1.0);
    }
"#;

let fragment_shader_src = r#"#version 120
    void main() {
    gl_FragColor = vec4(1.0, 1.0, 0.0, 1.0);
    }
"#;
</pre>

I manage to get it work but this syntax is really new to me, what does mean r#...# ?

Is there another way in the crate to get the proper GLSL for version 120 instead of 140 ?

**Comment by est31** [comment]
@bendeg they are raw string literals: https://doc.rust-lang.org/reference/tokens.html#raw-string-literals

> Is there another way in the crate to get the proper GLSL for version 120 instead of 140 ?

The glsl version is set by those pragmas. You can only change the OpenGL via the API, using the with_gl function on the context builder. https://docs.rs/glutin/0.22.0-alpha3/glutin/struct.ContextBuilder.html#method.with_gl
