### ISSUE TITLE
clear_color doesn't display the correct RGB color

### ISSUE THREAD

**Issue by mandeep** [glium/glium#1793]
Using glium version 0.25.1 and the following code:
```Rust
extern crate glium;

use glium::glutin;
use glium::Surface;


fn main() {
    let mut events_loop = glutin::EventsLoop::new();
    let window_builder = glutin::WindowBuilder::new()
        .with_dimensions((400.0, 400.0).into())
        .with_title("Fragula");
    let context_builder = glutin::ContextBuilder::new();
    let display = glium::Display::new(window_builder, context_builder, &events_loop).unwrap();

    let mut closed = false;

    while !closed {
        let mut target = display.draw();
        target.clear_color(0.122, 0.173, 0.227, 1.0);
        target.finish().unwrap();

        events_loop.poll_events(|event| {
            match event {
                glutin::Event::WindowEvent {event, .. } => match event {
                    glutin::WindowEvent::CloseRequested => closed = true,
                    _ => (),
                },
                _ => (),
            }
        });

    }
}
```
I receive the following window with the wrong RGB color:
![glium](https://user-images.githubusercontent.com/10521687/66800130-0f67ef00-eee2-11e9-94bd-a7589301e5a6.png)

Using C++ and libepoxy with similar code I receive the correct color as shown below:
![opengl](https://user-images.githubusercontent.com/10521687/66800183-41795100-eee2-11e9-8663-c94f2e7e14ad.png)

Here is the output of glxinfo if it helps:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)  (0x1616)
    Version: 18.3.6
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.6
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.3.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.3.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

**Comment by est31** [comment]
This is probably some color space issue. Not sure if a bug or not.

**Comment by ZeroX-DG** [comment]
I'm having this issue too. However I'm new to opengl so I can't really say much.

**Comment by Raz-Hemo** [comment]
`glutin::ContextBuilder` defaults to `sRGB=true`. Maybe that is what affects you?

**Comment by Raz-Hemo** [comment]
I've just discovered something weird. 
Setting sRGB to true/false in `ContextBuilder` works - When false, clearing something to 0.5 actually clears it to 188/255, and when true it actually clears it to 127/255.
However, I'm using a framebuffer to render color output first, and then copy the final buffer into the render target. This method completely disregards the sRGB setting, and always gives me the 188/255 result when I clear the framebuffer to 0.5 (no matter what the `color_srgb` parameter to `clear` is.)

**Comment by mandeep** [comment]
sRGB defaults to true. When setting it to false, the problem persists.

**Comment by est31** [comment]
@Raz-Hemo I don't know about the framebuffers, but for the textures at least there are srgb and non-srgb variants so the global srgb setting is not important to them.

**Comment by Raz-Hemo** [comment]
@est31 Yes, but textures used for framebuffers must have an UncompressedFloatFormat which has no sRGB distinction.

**Comment by mandeep** [comment]
I discovered the issue. Apparently, the command is `clear_color_srgb` and not `clear_color` as is expected. I'm not sure if this is because `ContextBuilder` defaults to srgb = true, or if it's due to something else. The docs do not make it clear what the difference is between these two methods and the function prototypes look similar.

**Comment by est31** [comment]
Alright then, closing. Happy to merge any PR to improve the docs. Thanks

**Comment by mandeep** [comment]
@est31 sounds good. I could submit a PR but I don't know what the difference should be between the two methods.

**Comment by est31** [comment]
See `src/ops/clear.rs` for the difference. Basically it disables/enables `GL_FRAMEBUFFER_SRGB` based on whether the `clear_color` or `clear_color_srgb` function is called. For the consequences see:

https://www.khronos.org/opengl/wiki/Framebuffer
