### ISSUE TITLE
Create Texture2d in multi thread - panics

### ISSUE THREAD

**Issue by AndreaCatania** [glium/glium#1798]
I'm writing a Multi Thread software, where in the main thread I create the object needed by Glium, like the window, the display (facade), etc..

Later, in another thread, I would like to construct a Texture2d but it crash. If I exec the same algorithm in the main thread it doesn't crash.

Do you have any idea?
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: (ContextWrapper { context: Context { context: X11(Windowed(ContextInner { xconn: 0x560b9196eda0, context: Glx(Context { xconn: 0x560b9196eda0, drawable: 54525955, context: 0x560b91abbaa8, pixel_format: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: None, srgb: true } }) })), phantom: PhantomData }, window: Window { .. } }, OsError("`glXMakeCurrent` failed: Ok(())"))', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("`glXMakeCurrent` failed: Ok(())")', src/libcore/result.rs:1165:5
```

**Comment by est31** [comment]
Texture2d's need access to the context object. Anything that needs access to context objects can't be done on separate threads. So e.g. you can generate meshes in a separate thread, but to upload them to the GPU you need to use the main thread again. OpenGL is an inherently single threaded API. If you are interested in APIs that support multithreading, look at vulkan, e.g. vulkano: https://github.com/vulkano-rs/vulkano

**Comment by AndreaCatania** [comment]
Thanks!
