### ISSUE TITLE
Unable to generate screenshot

### ISSUE THREAD

**Issue by hipstermojo** [glium/glium#1800]
I have copied the entire [screenshot example](https://github.com/glium/glium/blob/master/examples/screenshot.rs) code but it seems to only generate a blank image unless I type `WindowBuilder::new().with_visible(true)`. However I want the screenshot to be generated without the WindowBuilder being displayed. Is there a workaround to that?

**Comment by hipstermojo** [comment]
I am running version `0.26.0-alpha5` on Arch Linux

**Comment by est31** [comment]
Wayland or X11?

**Comment by hipstermojo** [comment]
It's running x11

**Comment by est31** [comment]
Confirmed. The bug exists since at least 78635fe52d602d7e391aa93b67ae5004d2a1e421 (can't go any older as the build is broken back there on newer compilers). If it's a regression then it most likely occurred in other software like X11.

**Comment by hipstermojo** [comment]
Is there a workaround to it or someone looking to fix the issue?

**Comment by est31** [comment]
No idea, not even sure whether it's even intended behaviour by X11.

**Comment by hipstermojo** [comment]
Is there a way to detect if a system is running x11. Because I can then just make the window pop up allowing the screenshot to be rendered correctly.

**Comment by est31** [comment]
https://docs.rs/winit/0.20.0-alpha4/winit/platform/unix/trait.EventLoopWindowTargetExtUnix.html#tymethod.is_x11

**Comment by hipstermojo** [comment]
Oh okay. I'll just close this then

**Comment by hipstermojo** [comment]
Sorry to reopen this but, when I ran this on Wayland, I got a `SIGSEGV` error.

**Comment by est31** [comment]
@hipstermojo that's an upstream bug: https://gitlab.freedesktop.org/mesa/mesa/issues/1731

I'll make a PR to fix X11.

**Comment by ducthotran2010** [comment]
I have the same issue when trying to screenshot with xvfb, even though I set `with_visible(true)`.
The method `display.read_front_buffer()` did work as expected.
Do you have any advices?
