### ISSUE TITLE
Question: Taking screenshot with Headless Glutin

### ISSUE THREAD

**Issue by hipstermojo** [glium/glium#1809]
Is it possible to get a screenshot of an image with a Headless Glutin backend? I would like to use such a feature for code that lives on a server thus cannot have a Window manager

**Comment by est31** [comment]
What about using xf86-video-dummy / Xvfb ?

**Comment by hipstermojo** [comment]
I will look at that as an option. Is it uncommon to use Headless Glutin for screenshots?

**Comment by est31** [comment]
> Is it uncommon to use Headless Glutin for screenshots?

Not really but I think glium certainly doesn't want you to prevent you from doing this. glium is just calling glReadPixels (as discussed in #1800). If you know of gl invocations to do screenshots in a headless way, feel free to suggest it or file a PR to add this to glium.

**Comment by est31** [comment]
Note: maybe the glutin/winit devs know more about how you can do headless screenshots: 
* https://github.com/rust-windowing/glutin
* https://github.com/rust-windowing/winit

**Comment by hipstermojo** [comment]
I will take a look

**Comment by yazgoo** [comment]
Hi, I'm having the same question: how can I render to an image without showing the window ? @hipstermojo did you do any progress on that ?

**Comment by hipstermojo** [comment]
I didn't have any luck with getting to render without a window sadly.

**Comment by yazgoo** [comment]
Will have a look at it.

**Comment by Boscop** [comment]
@yazgoo Did you figure it out? I want to do headless non-realtime rendering (to construct an 8k video frame by frame).
