### ISSUE TITLE
Attribute type U2U10U10U10Reversed does not work

### ISSUE THREAD

**Issue by avl** [glium/glium#1811]
When a vertex attribute has type U2U10U10U10Reversed, glium incorrectly reports size 1 when using glVertexAttribPointer, which is invalid according to OpenGL docs:

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml

This leads to the call failing, a diagnostic being printed, and then a program segfault (for me, using NVidia drivers on Linux).

I have a fix, and will make a pull request shortly.

**Comment by est31** [comment]
Fixed by #1812
