### ISSUE TITLE
Implicit naming convention 

### ISSUE THREAD

**Issue by InnocentusLime** [glium/glium#1827]
I haven't found this being mentioned in the docs for `implement_vertex` macros, but apparently the names of the fields of the struct you are using for a VBO must match the attribute names in the shader or else glium will panic (not return an error code!) claiming that an attribute "is missing in vertex array bindings".

**Comment by est31** [comment]
PR to point this out in the `implement_vertex` docs is welcome!

**Comment by InnocentusLime** [comment]
Okay. I'll create a PR for that! That should be simple... Just a pair of new lines. However, I am a bit confused why Glium prefers panicing with a scary message rather then generating an error code.

**Comment by InnocentusLime** [comment]
Created a PR for that. The id is #1841

**Comment by est31** [comment]
Fixed by #1841
