### ISSUE TITLE
Tutorial 01 doesn't match latest `glutin` version

### ISSUE THREAD

**Issue by ikamensh** [glium/glium#1831]
I've tried the tutorial 01 https://github.com/glium/glium/blob/master/book/tuto-01-getting-started.md and it doesn't work. First, it fails to resolve some names in `glutin`. Second, `glutin` has changed the signature of EventLoop:

>>>error[E0599]: no method named `poll_events` found for type `glium::glutin::event_loop::EventLoop<()>` in the current scope

I have used code from tutorial2 to fix this:

Fix is available in https://github.com/glium/glium/pull/1833

**Comment by est31** [comment]
Fixed by #1833
