### ISSUE TITLE
Rendering to textures on different threads?

### ISSUE THREAD

**Issue by Boscop** [glium/glium#1847]
I need to decode the input streams from multiple webcams/videos in parallel and write their frames to textures using glium.
Is it possible to render to a texture in a different thread than the main glium thread?
If yes, how? (So that it's thread-safe as far as opengl is concerned.)

`Texture2d` is not `Send`, so I'd have to create the texture in the decoding thread, but then how can I render it in the glium thread? I'd need to pass `texture.sampled()` in the glium thread but `Sampler<'s, Texture2d>` is not `Send` because `Texture2d` is not `Send`.
Is there any way? :)

**Comment by est31** [comment]
opengl allows for multiple independent contexts to be used on multiple threads, but not for multiple threads sharing one context. That's a basic design limitation. Vulkan is different as IIRC it allows more multi-threading.

**Comment by Boscop** [comment]
@est31 Would it be a solution to create a different context on each decoding thread? 
Can the textures then be rendered as part of a unified scene, by enabling the contexts to access the same textures?

**Comment by est31** [comment]
Coordinating this would be a fairly large change to glium. I doubt that it has the maintainer bandwidth to do it. If you disagree or know of a way which would include smaller changes, please say so.

**Comment by Boscop** [comment]
Not sure what the small changes would be, I just heard that opengl allows sharing textures between multiple contexts, but I didn't know it wasn't possible with glium..
