### ISSUE TITLE
GL_INVALID_FRAMEBUFFER_OPERATION on headless

### ISSUE THREAD

**Issue by esposm03** [glium/glium#1857]
I was messing with this library, and I found that trying to draw using  `Headless` instead of `Display` results in `GL_INVALID_FRAMEBUFFER_OPERATION`.
For example, [this code](https://pastebin.com/9TEubkWW), taken from `examples/tutorial-02.rs`, with only lines 7-9 changed, triggers [these messages](https://pastebin.com/U03wpt1D) when run, apparently once per frame.

**Comment by Boscop** [comment]
@esposm03 Headless doesn't seem well-supported: https://github.com/glium/glium/issues/1706

**Comment by fayalalebrun** [comment]
I have been investigating this issue and I believe this is what should happen. When you use glutin's `build_surfaceless` function to create a OpenGL context, it means that the display is created without a surface to draw to. Thus, this is the reason it fails.

However, if you try to draw to a texture, it will work just fine.

The usefulness of this is that you can create an OpenGL context even without a windowing system. That is, if glutin supports it.

I think that Glium should give a more useful error, but not being able to draw to the surface of a surfaceless display is the intended behaviour.

**Comment by esposm03** [comment]
Okay! I've abandoned the project in the mean time, but it may be useful for others. Closing the issue
