### ISSUE TITLE
`Uniforms::visit_values` should take emitter closure by `&mut` instead of by value.

### ISSUE THREAD

**Issue by Boscop** [glium/glium#1859]
https://docs.rs/glium/0.27.0/glium/uniforms/trait.Uniforms.html#tymethod.visit_values

Currently it takes the closure by value, making it unnecessarily inconvenient to implement custom types that contain multiple types that impl `Uniforms`, which is needed for dynamic uniforms.

`visit_values` should be changed to 
```rust
fn visit_values<'a, F: FnMut(&str, UniformValue<'a>)>(&'a self, _: &mut F)
```
so that it's possible to call `visit_values` on multiple members sequentially, passing the emitter closure to each call without consuming it.

**Comment by est31** [comment]
@Boscop you are aware that `&mut T` implements all the fn traits of `T`?

**Comment by Boscop** [comment]
Ah right -.-
