### ISSUE TITLE
missing Debug impl on Display

### ISSUE THREAD

**Issue by wolfiestyle** [glium/glium#1865]
can't `#[derive(Debug)]` on anything that contains a `glium::Display` field.

**Comment by est31** [comment]
PRs welcome! I wonder what a useful debug impl would be.

**Comment by PonasKovas** [comment]
Uhm isn't `Display` in `glutin` and not in `glium`?

Anyway I don't believe it should implement `debug` since there's no useful debugging info that it could ever print. Just implement the `Debug` trait for your structs yourself

**Comment by est31** [comment]
@PonasKovas Display is in the `glutin` backend of glium. https://docs.rs/glium/0.27.0/glium/backend/glutin/struct.Display.html

I guess they refer to that?

**Comment by est31** [comment]
No it's part of glium: https://github.com/glium/glium/blob/1f90a6d98054b8186a1f86643bd980ea61ed2863/src/backend/glutin/mod.rs#L36

This is the right repo for that. But I don't know what a debug impl should contain.

**Comment by PonasKovas** [comment]
In my opinion there's no useful info that you could print for a `Display`, so if you choose to implement `Debug` for it, then just print `[Display]` or something.

**Comment by est31** [comment]
Yeah let's go with that. Maybe `[glium::backend::glutin::Display]`? If there is any desire to print something else, it can be improved upon.

**Comment by PonasKovas** [comment]
I'd go with just `glutin::Display` since glutin is a separate crate

**Comment by est31** [comment]
Again, the Display type here is part of the glium crate.
