### ISSUE TITLE
No info about IndexBuffer's slice argument

### ISSUE THREAD

**Issue by lucaszanella** [glium/glium#1872]
I'm trying to draw a simple square made of 2 triangles:

```
glium::VertexBuffer::new(
            &display,
            &[
                Vertex {
                    position: [-1.0, -1.0, 0.0],
                    color: [0.0, 1.0, 0.0],
                },
                Vertex {
                    position: [1.0, -1.0, 0.0],
                    color: [1.0, 1.0, 0.0],
                },
                Vertex {
                    position: [-1.0, 1.0, 0.0],
                    color: [0.0, 0.0, 0.0],
                },
                Vertex {
                    position: [1.0, 1.0, 0.0],
                    color: [1.0, 0.0, 0.0],
                },
            ],
        )
        .unwrap()
```

On pure OpenGL I simply did `glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);` which means: use the triangle strip technique, begin in index 0, draw 4 vertices. 

How would it be translated to `IndexBuffer`?
```

let index_buffer =
        glium::IndexBuffer::new(&display, PrimitiveType::TriangleStrip, &[0u16,1,2]).unwrap();
```

I see it has the `PrimitiveType::TriangleStrip`, but what is the slice argument? `&[0u16,4]` didn't work for me (black screen). Trying random values on the slice gives me different images. PS: I'm using a fixed white color to test all this. I modified the `triangles.rs` example.

I searched on the book, it does not explain `IndexBuffer`, and neither the documentation explains.

**Comment by est31** [comment]
Have you tried `[0,1,2,3,4]`?

**Comment by lucaszanella** [comment]
@est31 thanks, now it makes sense. It's literally a buffer of indices. Correct value is `[0,1,2,3]` for my case since I have 4 vertices
