### ISSUE TITLE
How to draw at high frame rate?

### ISSUE THREAD

**Issue by lucaszanella** [glium/glium#1878]
The only event I saw that gets close to a redraw request is

`glutin::event::Event::RedrawRequested(window_id)`

but this is only issued when the OS invalidates the window data or the application calls it. However calling the application isn't good because I don't know at which rate I can call it. It'd be better to get a call for each frame of the window and then issue the OpenGL drawing when this happens. 

I'm writing a video renderer so it must play at the highest frame rate possible. How can I achieve that?

None of the window events match a pure redraw in the sense that it's called for every frame

**Comment by est31** [comment]
That's best a question asked in glutin communities: https://github.com/rust-windowing/glutin#contact-us
