### ISSUE TITLE
PixelBuffer only supports full buffer write 

### ISSUE THREAD

**Issue by lucaszanella** [glium/glium#1879]
There are cases in which we need to upload to a pixel buffer in parts instead of sending the entire data. For example, I'm writing a video player, and it uses ffmpeg decoded video. The problem is that ffmpeg may output decoded video with a stride:

```
----------------------------###
----------------------------###
----------------------------###
...
----------------------------###
```
so the video frame is aligned properly in memory. For this reason, I need to write to the `PixelBuffer` in parts, removing the leftover of each line, so this arrives in the `PixelBuffer`:

```
----------------------------
----------------------------
----------------------------
...
----------------------------
```

This is my code:

```
pub fn stride_respect_upload_pixel_buffer(
        pixel_buffer: &PixelBuffer<u8>,
        width: u32,
        height: u32,
        linesize: usize,
        slice: &[u8],
    ) {
        for line in 0..height {
            let current_line_start = (line * width) as usize;
            let s = &slice[(current_line_start)..(current_line_start + linesize)];
            pixel_buffer.write(s);
        }   
    }
```

It panics on `pixel_buffer.write(s);` because I'm writing just the first line of the video data instead of the entire video data. Obviously I could copy everything into a new slice and then send to the `PixelBuffer` but this would be extremely inneficient, specially for decoded video data.

Shouldn't PixelBuffer support partial writes? At least with another write method called `write_partially`? Maybe then the user could call `commit()` on the end of the write just so glium can verify it wrote the exact ammount of data matching the `PixelBuffer`'s size.

**Comment by est31** [comment]
You can call `as_mut_slice` on the buffer to get a BufferSlice, then call `slice` to get a sub-slice, then you can call write on that.

**Comment by lucaszanella** [comment]
@est31 but according to the docs, both `slice` and `as_mut_slice` perform no OpenGL operation:

_This method builds an object that represents a slice of the buffer. No actual operation OpenGL is performed._

Therefore, `glBufferSubData` will not be called for the slice I write

**Comment by est31** [comment]
Have you tried it?

That note only refers to the action of creating the slice.

Check the code, it really calls something when you do `.write`: https://docs.rs/glium/0.28.0/src/glium/buffer/view.rs.html#886-890

**Comment by lucaszanella** [comment]
@est31 oh ok I thought you were talking about calling write on a pure slice, not a custom slice of glium, thanks
