### ISSUE TITLE
Loading SPIR-V shaders as glium `Program`?

### ISSUE THREAD

**Issue by Boscop** [glium/glium#1890]
Apparently, with opengl 4.6 (or extension `ARB_gl_spirv`) it's possible to load SPIR-V shaders with OpenGL.
Can I just use [`ProgramCreationInput::Binary`](https://docs.rs/glium/0.28.0/glium/program/enum.ProgramCreationInput.html) or how would it be possible with glium? (I have opengl 4.6)

Edit: Ah, it has to use [`GL_SHADER_BINARY_FORMAT_SPIR_V`](https://www.khronos.org/opengl/wiki/SPIR-V).. 
Could SPIR-V be supported in glium by adding a variant `ProgramCreationInput::SpirV` that uses this?

Because I'd really like to load [shaders written in Rust compiled to SPIR-V](https://github.com/embarkstudios/rust-gpu) in glium :)

**Comment by est31** [comment]
PRs welcome!

**Comment by Boscop** [comment]
@est31 In case the opengl version is less than 4.6, the `ARB_gl_spirv` extension would need to be enabled to support this. What's the recommended way to allow code to tell glium to enable an extension?

**Comment by Boscop** [comment]
@est31 I tried to implement loading of SPIR-V shaders here: https://github.com/glium/glium/compare/master...Boscop:spirv-shaders

Unfortunately, when I run the `screenshot-spirv` example, it fails with:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LinkingError("glLinkProgram triggered GL_INVALID_OPERATION")', examples/screenshot-spirv.rs:38:12

Is it invalid to combine a GLSL vertex shader with a SPIR-V fragment shader?

If someone can help me make progress with this, I'd really appreciate it :)

**Comment by Boscop** [comment]
I fixed it, now it's working :)

The issue was that apparently a GLSL vertex shader cannot be combined with a SPIR-V fragment shader, both must be SPIR-V (or GLSL).
https://www.khronos.org/opengl/wiki/SPIR-V#Linking_SPIR-V
