### ISSUE TITLE
Can we have a new release with the updated winit dependency?

### ISSUE THREAD

**Issue by willemv** [glium/glium#1897]
`imgui-rs/imgui-rs` and `Yatekii/imgui-wgpu-rs` need a new release of glium to be able to upgrade their dependency on winit:
* https://github.com/imgui-rs/imgui-rs/pull/404
* https://github.com/Yatekii/imgui-wgpu-rs/pull/41

Can the maintainer please publish a new glium release to crates.io ?

**Comment by est31** [comment]
Right now I'm waiting for #1894 and #1895 to be merged but if it turns out this won't happen during next week, I'll cut a new release regardless.

**Comment by willemv** [comment]
Great, thank you!

**Comment by willemv** [comment]
🎉
