### ISSUE TITLE
glium has triggered an OpenGL error during initialization

### ISSUE THREAD

**Issue by axolotl-inc** [glium/glium#1920]
When compiling and running a simple program that draws a single triangle to the screen, glium throws this error, complaining about something to do with invalid qualifiers:

glium has triggered an OpenGL error during initialization. Please report this error: https://github.com/glium/glium/issues
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("0:3(2): error: `in\' qualifier in declaration of `position\' only valid for function parameters in GLSL 1.20\n", Vertex)', src/main.rs:44:103
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I hope someone has a fix for this, and thank you in advance.

**Comment by fayalalebrun** [comment]
It sounds like there's in shader compilation. What's the source of the shader you're trying to compile?

**Comment by Melchizedek6809** [comment]
Yeah does sound like a problem with the shader, if it's still a problem just reopen this issue and post the shader/program then we can figure out what's the cause.
