### ISSUE TITLE
Glium Display Does Not Close After Drop, Windows

### ISSUE THREAD

**Issue by bayswaterpc** [glium/glium#1932]
I'm having an issue where the Display remains frozen on screen after exiting an app process.  I'm trying to set up an example of a popup rust modal using Egui from a simple c++ commandline app.  You can see it at my [example repo](https://github.com/bayswaterpc/visual_studio_cpp_egui_demo) & pertinent code in [this file](https://github.com/bayswaterpc/visual_studio_cpp_egui_demo/blob/main/egui_glium_pure/src/lib.rs)

I'm trying to explicitly drop the window here but that doesn't kill it either.  Based on the discussion in [winit/issues/434](https://github.com/rust-windowing/winit/issues/434) it just dropping it seems to be the right approach for killing the window.

```rust
...
            glutin::event::Event::WindowEvent { event, .. } => {
                egui.on_event(event, control_flow);
                match control_flow {
                    glutin::event_loop::ControlFlow::Exit => {
                        println!("exiting");
                        std::mem::drop(display.gl_window().window());
                        println!("Dropped Winit Window");
                        std::mem::drop(display.gl_window());
                        println!("Dropped Gl Window")
                        //std::mem::drop(display);
                    }
                    _ => {
                        display.gl_window().window().request_redraw(); // TODO: ask egui if the events warrants a repaint instead
                    }
                }
            }
...
```

I'm saw some old similar bugs but those seemed to be fixed in Winit [/rust-windowing/winit/issues/7](https://github.com/rust-windowing/winit/issues/79), [winit/pull/416](https://github.com/rust-windowing/winit/pull/416).

And then some even older things in glium #831, #992
General build info
- Windows 10
- DirectX 12
- Processor AMD Ryzen 7 5800X
- Rust Nightly

**Comment by maroider** [comment]
After talking on Discord, we've determined that it *looks* like `DestroyWindow` is being called, but the window is nevertheless sticking around for longer than it should.

As you suggested on Discord, it may be an idea to upgrade to Winit 0.25.0 to see if it's something that's been fixed already. You can do this for yourself by adding a `[patch.crates-io]` section like so:

```toml
[patch.crates-io]
winit = { git = "https://github.com/rust-windowing=winit", tag = "v0.25.0" }
```

PS: I don't quite understand why it is you've specified that you're using(?) DirectX 12 when you're clearly using OpenGL.

**Comment by est31** [comment]
What about replacing `tag = "..."` with `branch ="c05952b813a84492338debc75bb0ac21ebc767dd"`? Does that work?

**Comment by bayswaterpc** [comment]
So I've scoped this error to it's own [repo](https://github.com/bayswaterpc/egui_glium_pure_window_not_closing).  You can test it out in pure rust now, no visual studio or c++ step.

In short no it does not work.  I set the patch so it's like
```
[patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit", branch ="c05952b813a84492338debc75bb0ac21ebc767dd" }
```

Gives me the following error on `cargo update`
```
    Updating git repository `https://github.com/rust-windowing/winit`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for dependency `winit`

Caused by:
  Unable to update https://github.com/rust-windowing/winit?branch=c05952b813a84492338debc75bb0ac21ebc767dd

Caused by:
  failed to find branch `c05952b813a84492338debc75bb0ac21ebc767dd`

Caused by:
  cannot locate remote-tracking branch 'origin/c05952b813a84492338debc75bb0ac21ebc767dd'; class=Reference (4); code=NotFound (-3)
```

**Comment by est31** [comment]
Oh sorry you the key is called `rev` instead of `branch`.

**Comment by bayswaterpc** [comment]
Doesn't fix it, but also it doesn't seem to have any affect as it adding that patch just causes this
```
PS C:\Users\BayswaterPC\egui_glium_pure_window_not_closing> cargo update
    Updating git repository `https://github.com/rust-windowing/winit`
    Updating crates.io index
    Removing winit v0.24.0
      Adding winit v0.24.0 (https://github.com/rust-windowing/winit?rev=c05952b813a84492338debc75bb0ac21ebc767dd#c05952b8)
```
I was expecting to see 0.25, unless there was a smaller fix in 0.24 you were hoping would take affect

**Comment by est31** [comment]
The 0.24 is intended, because if it read 0.25, cargo wouldn't replace it (as can be observed above in the thread). Cargo needs the replaced version to be semver-compatible with the new version. The commit hash points to a version of winit that was after the 0.24 release, but already had the PR applied that you mentioned.

**Comment by est31** [comment]
Does the issue persist if you remove the entire render loop, aka comment out the `event_loop.run_return` call?

**Comment by bayswaterpc** [comment]
Yeah it looks like the dialog does persist even with the loop commented out

![image](https://user-images.githubusercontent.com/78702667/120571245-b6670a80-c3e7-11eb-9bb5-40c41602ba3d.png)

**Comment by est31** [comment]
@bayswaterpc thanks. It looks like this bug is a glutin issue because the active code doesn't use any of the glium crate any more. To make sure, you can try replacing the glium dependency with glutin and check whether it still produces the bug in that setting. I'm closing this issue as it doesn't look like a glium problem. I recommend you [file a glutin issue](https://github.com/rust-windowing/glutin/issues/new/choose) instead.

**Comment by bayswaterpc** [comment]
kk thanks for the info!
