### ISSUE TITLE
per_instance() incorrectly returns InstancingNotSupported on GLES 3

### ISSUE THREAD

**Issue by cosmicchipsocket** [glium/glium#1935]
Was busy porting my game engine to Emscripten and noticed that it was erroring out because per_instance() was returning Err(InstancingNotSupported). I looked around and it turns out that WebGL 2 does infact support instancing, so I modified glium to remove the OpenGL version and extension checks and it started working.

The per_instance() functions should return successful if the current context is GLES 3 or newer.

**Comment by est31** [comment]
Fixed by #1936
