### ISSUE TITLE
high cpu usage, llvm_pipe threads 

### ISSUE THREAD

**Issue by lucaszanella** [glium/glium#1945]
I'm developing inside a VM. I'm rendering video with OpenGL. I noticed that my app process CPU usafe was in 100% using `top`. I did `top` then `H` to show the threads and found this:

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                
         
 247759 root      20   0 3491496 104400  64676 R  32.2   1.0   0:02.98 glium_app           
 247785 root      20   0 3491496 104400  64676 S  22.9   1.0   0:01.89 llvmpipe-0             
 247786 root      20   0 3491496 104400  64676 S  21.9   1.0   0:01.71 llvmpipe-1             
 247792 root      20   0 3491496 104400  64676 S  20.9   1.0   0:01.83 llvmpipe-7             
 247789 root      20   0 3491496 104400  64676 S  20.3   1.0   0:01.60 llvmpipe-4             
 247790 root      20   0 3491496 104400  64676 S  20.3   1.0   0:01.64 llvmpipe-5             
 247787 root      20   0 3491496 104400  64676 S  19.9   1.0   0:01.70 llvmpipe-2             
 247788 root      20   0 3491496 104400  64676 S  19.9   1.0   0:01.61 llvmpipe-3    

```  

lots of llvm_pipes. According to https://docs.mesa3d.org/drivers/llvmpipe.html,

> The Gallium llvmpipe driver is a software rasterizer that uses LLVM to do runtime code generation. Shaders, point/line/triangle rasterization and vertex processing are implemented with LLVM IR which is translated to x86, x86-64, or ppc64le machine code. Also, the driver is multithreaded to take advantage of multiple CPU cores (up to 8 at this time). It’s the fastest software rasterizer for Mesa.

This looks like it does vertex processing in runtime. 

What is happening? Why 100% of my CPU is being used for this?

**Comment by est31** [comment]
@lucaszanella you might have to pass OpenGL acceleration to your VM. This doesn't seem like a glium bug so I'm closing it. Even if it's a bug about deciding the wrong OpenGL backend, it's a context creation issue, so falls within the domain of glutin.
