### ISSUE TITLE
Framerate inconsistent on windows (on moving the mouse)

### ISSUE THREAD

**Issue by sawcce** [glium/glium#1958]
# Issue

When following the glium tutorial everything works fine except when I switch from windows to linux the framerate is extremely inconsistent and it gets weirder:
- The framerate doesn't seem to match the 17 ms interval
- The framerate gets faster when moving the mouse

Why does that happen ?
I even copied the code to see if I had made a mistake but not it's still the same

BEcause from what I've understood we put a delay of 17 ms between each frames for a fixed framerate, right ?

**Comment by est31** [comment]
Which of the tutorial examples are you talking about? Can you show code? Note that the tutorial is mainly meant to teach you the basics of OpenGL and glium, not to avoid all possible sets of bugs.

**Comment by sawcce** [comment]
> Which of the tutorial examples are you talking about? Can you show code? Note that the tutorial is mainly meant to teach you the basics of OpenGL and glium, not to avoid all possible sets of bugs.

Well, I basically just followed the glium book on GitHub and stopped at tutorial 5 I even copied the code and the bug still happens...

**Comment by est31** [comment]
Sorry but I need actual code. Vague descriptions don't help.

**Comment by sawcce** [comment]
> Sorry but I need actual code. Vague descriptions don't help.

[Code](https://github.com/glium/glium/blob/master/examples/tutorial-05.rs)

Ah sorry 😅 , it felt obvious to me when I said I copied the code from the tutorial to try and fix the error that I just took the code from the repo

I feel like the dumbass who tries to describe his issue without giving the resources to fix it now x)

**Comment by est31** [comment]
@sawcce how do you do the FPS printing?

**Comment by sawcce** [comment]
> @sawcce how do you do the FPS printing?

I actually removed it due to the fact that I thought it was broken but it wasn't, I just added 1 to a var every loop call and reset every 1 sec

https://gyazo.com/f3b3a74cbd80724381caa264ae274813 btw a video clip of the issue idk if the crappy framerate of gyazo it'll show

**Comment by sawcce** [comment]
ik this is not a real answer but I have deleted that part of the code and like the fps problem is visible by eye

**Comment by sawcce** [comment]
also could you reopen the issue?

**Comment by est31** [comment]
@sawcce I'm still not sure it's a bug. If it is, this seems like a glutin bug to me. glutin handles the event loop, events, etc. glium only handles the rendering part, but this render is re-issued at each frame.

https://github.com/rust-windowing/glutin/issues
