### ISSUE TITLE
Application crashes about 50% of the time on startup

### ISSUE THREAD

**Issue by Rami-Slicer** [glium/glium#1962]
When compiling the code in `examples/tutorial-01.rs` I'm getting this error about 50% of the time, totally randomly:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
<app>: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```
The other half of the time it starts up, no problem.

**Comment by unlimitedbacon** [comment]
I am having the same problem.

**Comment by est31** [comment]
Can you reproduce the problem when running the glutin examples from https://github.com/rust-windowing/glutin ?

**Comment by Rami-Slicer** [comment]
> Can you reproduce the problem when running the glutin examples from https://github.com/rust-windowing/glutin ?

Yes, I'm getting the same error with the glutin examples. Should I report the issue there instead?

**Comment by est31** [comment]
> Should I report the issue there instead?

Yeah, you should report it at their issue tracker as it is no glium bug. Thanks!
