### ISSUE TITLE
Sometimes my program just randomly crashes?

### ISSUE THREAD

**Issue by eboatwright** [glium/glium#1999]
When my program, sometimes it works, and sometimes it crashes with this error
```
[xcb] Unknown sequence number while processing queue                                  
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.                                                                   
testing: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

**Comment by fayalalebrun** [comment]
Could you give more information on your environment? Driver versions, X or Wayland, GPU.
Could you open the program with rust-gdb and get a backtrace when the error takes place?

Does this happen with any of the examples as well?

**Comment by eboatwright** [comment]
It's probably just my old laptop's graphics card. It's a Macbook Pro mid-2012

**Comment by mostthingsweb** [comment]
I don't think it's just your laptop: https://github.com/rust-windowing/glutin/issues/1034

It happens to me too on a modern-ish 2018 HP ZBook 15 G4 laptop.

**Comment by est31** [comment]
Hrmm seems like a glutin issue? Or maybe the bug lurks in the driver, but I don't think this is a glium issue.
