### ISSUE TITLE
Shader Error In Tutorial

### ISSUE THREAD

**Issue by jhannyjimenez** [glium/glium#2011]
I just wanted to let you all know that you forgot to include the '#version 140' in your shader code under Section 2. Drawing a Triangle. This leads to a fragment shader error. Thank you.

**Comment by Melchizedek6809** [comment]
Just looked at the book and example code, both seem to have `#version 140` in the beginning of the vertex and fragment shaders. If it's still missing somewhere just reopen this issue with a link to the code in question.
