### ISSUE TITLE
How to use gl_FragDepth in fragment shader?

### ISSUE THREAD

**Issue by mostthingsweb** [glium/glium#2021]
I can write to gl_FragDepth in my fragment shader, but how do I get the value in my Rust code?

**Comment by mostthingsweb** [comment]
For context, I'm trying to implement what is described here under "Color Ranges": https://physicspython.wordpress.com/2020/03/04/visualizing-the-mandelbrot-set-using-opengl-part-2/.

**Comment by Melchizedek6809** [comment]
You could look at the shadow_mapping example for inspiration, although there the DepthTexture2D is just passed to another shader stage and not read out into Rust. There is also a mandelbrot renderer in the compute_image example, although that one seems to take a different approach.
