### ISSUE TITLE
FT: Prevent panicking in unmatched vertex attributes and missing attributes

### ISSUE THREAD

**Issue by rnd-ash** [glium/glium#2030]
This is a totally optional point of view.

With some apps and meshes, the data is already ready to be sent directly to the GPU, but might not match perfectly with the OpenGL Vertex shader, but OpenGL can still handle it and render the meshes correctly.

Also, missing vertex attributes should not necessarily causes a hard panic. The shader will still run fine with missing data.

Therefore, maybe it should be better to make panicking under these conditions a feature?

I've tested removing the panic! calls in my [own branch](https://github.com/rnd-ash/glium/commit/f7d0596baccc2075da1194c00f9737f708ca2742) and things work fine for my use case.

**Comment by est31** [comment]
Yeah OpenGL is a bit more tolerant but it is likely working due to chance. The checking helps prevent bugs so I don't want to remove it.

**Comment by rnd-ash** [comment]
Could it be possible to then put it behind a feature flag (On by default), so If for example you know exactly what you are doing, you can still use glium without it panicking.
