### ISSUE TITLE
Tutorial #3 isn't working

### ISSUE THREAD

**Issue by Local-Trash** [glium/glium#2033]
I'm trying to learn opengl and I followed the tutorial and I got stuck on tutorial 3. I tried everything until I copied the source code from github and it still doesn't work. The triangle appears, but it stays on the side and doesn't move.

**Comment by Melchizedek6809** [comment]
Are you maybe passing ` &glium::uniforms::EmptyUniforms` instead of `&uniform! { t: t }` to target.draw? I think that line was supposed to be changed in the final block, at least that might explain the Problem.

**Comment by Local-Trash** [comment]
I check that and it worked. Thankyou.
