### ISSUE TITLE
Compute Shader Examples Not Working

### ISSUE THREAD

**Issue by hindlet** [glium/glium#2034]
When trying to run the gpgpu and image_compute examples I get this error:

![image](https://user-images.githubusercontent.com/79304662/209735721-5f846e88-7a04-4ce6-bdf6-e151515275fd.png)

I'm not sure how to fix it, because it's example code. does anyone know what to do about it?

**Comment by Melchizedek6809** [comment]
What machine are you trying this example on? They both seem to work on my machine at least, so it might be a compatibility issue.

**Comment by hindlet** [comment]
I'm running them on a MacBook Pro from 2017, with a Radeon pro 560 gpu and MacOs Ventura

**Comment by Melchizedek6809** [comment]
Ah ok, that's a problem since it seems MacOS only supports up to OpenGL 4.1 while compute shaders require OpenGL 4.3

**Comment by hindlet** [comment]
Ah right, that makes sense, I'll see if there's a workaround but otherwise I can look into other graphics libraries, thank you for your help

**Comment by Melchizedek6809** [comment]
Glad to be of help, one workaround might be running GNU/Linux on that machine, since the GPU should be capable of 4.6 :)

**Comment by est31** [comment]
Seems resolved, so I'm closing.
