### ISSUE TITLE
Buffer trait for VertexBuffer and IndexBuffer

### ISSUE THREAD

**Issue by rornic** [glium/glium#2042]
I'm currently working on a [Minecraft clone](https://github.com/rornic/rustcraft) and using glium for my renderer. To render the world, I'm allocating one large VBO and IBO, and allocating/re-allocating sections of them to each 'chunk' that makes up the world.

While implementing allocation, I noted that there was no common interface across vertex buffers and index buffers in glium. To reduce code duplication I had to create [my own buffer trait ](https://github.com/rornic/rustcraft/blob/main/src/render/renderer.rs#L287)and implement it on both. It effectively just wraps the `slice` function on glium vertex buffers and index buffers, as well as some other utilities making it useful for me.

A common interface across buffers is probably something that'd be useful to glium. I'm opening this issue to discuss the feature, and am happy to implement it if it sounds useful.

**Comment by Melchizedek6809** [comment]
Oh nice, sounds like a fun project. I'm wondering what this would enable or simplify, do you have an example in mind?
