### ISSUE TITLE
Frame rate issues in examples

### ISSUE THREAD

**Issue by justincredible** [glium/glium#2043]
Windows 10.
NVIDIA GeForce GTX 1660
glium 0.32.1

The frame rate  is quite bad when running the tutorial-14 and shadow_mapping examples. This is likely a glutin bug, but I found a workaround by moving the WaitUntil assignment to the end of the event loop.

A bad frame rate also appears in the fxaa example but it is more subtle. The issue there is resolved by changing line 40 in mod.rs
from
`next_frame_time = Instant::now() + Duration::from_nanos(16666667);`
to
`next_frame_time += Duration::from_nanos(16666667);`
or by calculating the next frame time before the event loop.

**Comment by Melchizedek6809** [comment]
Are things also resolved by not setting the control_flow to `WaitUntil` and instead put all the draw code into a handler for `glutin::event::Event::RedrawEventsCleared` with a call to `display.gl_window().window().request_redraw();` at the end for continuous rendering?

That's at least the way it's being done in the glutin example and should work with whatever refresh rate the system is running at.

**Comment by justincredible** [comment]
I tried this out with the tutorial-14 example and it also resolves the issue there. It worked with or without the `request_redraw` call and even while leaving the existing `WaitUntil` assignment at the beginning of the event loop closure.

**Comment by Melchizedek6809** [comment]
Glad to hear that this fixes the problem.

I've checked with the winit/glutin folks over on Matrix and it seems that the currently preferred way would be to call `request_redraw` in the handler for `RedrawEventsCleared`, and then render the scene in respone `RedrawRequested` events. So the examples seem out-of-date.

Though this will probably change again once https://github.com/rust-windowing/winit/issues/2412 gets implemented.
