### ISSUE TITLE
DepthRenderBuffer errors with zero size

### ISSUE THREAD

**Issue by justincredible** [glium/glium#2044]
[error_renderbuffer.txt](https://github.com/glium/glium/files/10928723/error_renderbuffer.txt)

Windows 10
NVIDIA GeForce GTX 1660
glium 0.32.1

This error output appears on use of a `DepthRenderBuffer` created with either a zero width or height. The attached file was generated from the FXAA example by minimizing the window, but resizing the window height to zero has the same result.

It is easy enough to avoid using or even creating a zero sized `DepthRenderBuffer`, but I was surprised that I do not see errors when the `Texture2d` is created with a zero width or height. When calling OpenGL directly, creating a framebuffer with a zero-sized texture or renderbuffer results in a framebuffer status of GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT.

**Comment by Melchizedek6809** [comment]
Thanks for reporting this issue, took me a while to reproduce it since it only seems to occur on Windows. The linked PR should fix that issue.

**Comment by justincredible** [comment]
Yes, the PR works well. Thanks for addressing this.

**Comment by Melchizedek6809** [comment]
Thank you for testing!
Seems to be the same issue, I've added a fix to the existing PR, the compute_image example also seems to have issues when minimized on Windows, though it seems to have a different cause.

**Comment by justincredible** [comment]
That's good to know, I've run the compute shader examples but have not really looked into them yet.
