### ISSUE TITLE
Option to disable default features for `glutin`

### ISSUE THREAD

**Issue by negamartin** [glium/glium#2045]
Hello,

I had used `glium` a long-ish time ago, and just started a new project with the newest version. It turns out the experience on Linux is not so good:

1. By default just adding `glium` as a dependency requires `glutin` and therefore `winit` with all of their default dependencies, which include a whole text rendering system for Wayland systems that require the app to do CSD (client side rendering) of the window decorations. Not only is this an incredible amount of code that bloats the executable to about 100MB (!), it also seems to default to using the system `freetype` library, which requires `cmake` and crashes if `cmake` is not installed.
2. One solution is to use the `wayland-csd-adwaita-notitle` feature on `winit`, but it turns out that it is impossible to turn default features off for `winit` (as far as I can tell), because `glium` requires `glutin` with default features, and that always enables `wayland-csd-adwaita` on `winit`.

The end result is that it's impossible to remove default features from `winit` if using `glium`.

One possible solution is to split the `glium` feature into `glium` and `glium-default`, such that the `glium` feature enables `glium` integration but without any `glium` features, and `glium-default` enables the default feature set of the `glium` dependency.

**Comment by est31** [comment]
This might be an approach, and in general I do support making more things optional. I think this should be talked about once #2036 is merged.

**Comment by Melchizedek6809** [comment]
Hey there,

I've been cleaning up the dependencies for #2036 and winit is no longer a dependency for glium.

Additionally glutin is set to `default-features = false` since users need to pull in both glutin and winit to create a glium context, that way the users can easily specify the features they prefer.

Would be great if you two could look over the changes since I'm not that experienced with cargo and might have overlooked something.

**Comment by Melchizedek6809** [comment]
Should be fixed now that the PR has been merged, if there's something you'd like to do different then just reopen this issue so we can look at it again.
