### ISSUE TITLE
Draw two different textures using one shader program.

### ISSUE THREAD

**Issue by timofeev1995** [glium/glium#2048]
Hi!

I have a strange problem, Im sure that Im doing something wrong. Will be very appreciated, if you can help.

I have a simple shader, which draws a small square in my window. Also I create two textures: lets call them "red" and "green". My goal is to draw them both: lets say, one in a bottom left quarter, one in the upper right one.

```
let image_red = image::open("src/ui/resources/red.png")
        .unwrap()
        .to_rgba8();
let image_red_dimensions = image_red.dimensions();
let image_red = glium::texture::RawImage2d::from_raw_rgba_reversed(&image_red.into_raw(), image_red_dimensions);
let red_texture = glium::texture::Texture2d::new(&display, image_red).unwrap();

let image_green = image::open("src/ui/resources/green.png")
        .unwrap()
        .to_rgba8();
let image_green_dimensions = image_green.dimensions();
let image_green = glium::texture::RawImage2d::from_raw_rgba_reversed(&image_green.into_raw(), image_green_dimensions);
let green_texture = glium::texture::Texture2d::new(&display, image_green).unwrap();

let program = glium::Program::from_source(
            display,
            &vertex_shader_src_code, // actually simpliest one
            &fragment_shader_src_code, // just applies texture
            None,
)
        .unwrap();
// ...
// main loop
// ...

let mut target = display.draw();
target.clear_color_srgb(0.52, 0.41, 0.22, 1.0);

let shape_red = vec![... // bottom left quarter, does not matter here
let indices = glium::index::NoIndices(glium::index::PrimitiveType::TriangleStrip);
let vertex_buffer = glium::VertexBuffer::new(display, &shape).unwrap();
let uniforms = uniform! {
            texture: &red_texture,
};
target.draw(
            &vertex_buffer,
            indices,
            &self.program,
            &uniforms,
            &Default::default(),
).unwrap();

// and the same code for green one, but with different vertexes position and according red texture, initialized above
let shape_green = // upper right quarter, does not matter here
...

```

And i get the result: both of my squares are green => both of them have the texture, which I loaded last. 
1. If I switch red and green textures initialization order => I get the red one for both of squares, again, the last one.
2. If I don\t draw green one (second) square in the example above (just initializing texture and comment draw call), even then I get my first square green.
3. I can get the first square red if and only if I comment the following line:
`let green_texture = glium::texture::Texture2d::new(&display, image_green).unwrap();`

Can you please give me piece of advice, how to debug this kind of behaviour? I'm sure I'm doing something wrong, but can not see yet.

Thank you in advance, really appreciated. And thank you for glium!

**Comment by Melchizedek6809** [comment]
Hey there,

could you maybe upload a complete program with textures/shaders, for example here on GitHub, to look at?

Since at least on first glance the code here looks alright to me, and as long as the second square passes the `green_texture` as a uniform things should work.

**Comment by timofeev1995** [comment]
Yes, sure.
Thank you for your response!

My os is macos 11.2.2.
My cargo.toml is:
```
[package]
name = "bug_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = { version = "0.32.1", default-features = true }
image = "0.23"
```

Minimal example to reproduce can be found here: https://gist.github.com/timofeev1995/f2dfa2bae26c5476d94c0b4c24e84513
Result is attached below.
<img width="795" alt="image" src="https://user-images.githubusercontent.com/43988181/225108402-f42b2d59-21d2-4a8a-a989-64dd1ee97542.png">

**Comment by Melchizedek6809** [comment]
Ah alright, now I see the problem, the name of the texture uniforms doesn't match between the fragment shader and the `uniform!` macro, it works as expected if I change the name of the uniform to `tex` in the `uniform!` macro and the fragment shader, the texture thats initialized first is probably used because it defaults to the first texture unit.

**Comment by timofeev1995** [comment]
Oh, what an inattention by me. What a shame 😄 
Thank you so much for your time and your help.

**Comment by Melchizedek6809** [comment]
Happy to be of service.

**Comment by Melchizedek6809** [comment]
@est31 I think this issue can be closed

**Comment by est31** [comment]
Closing as per comment above. Thanks for helping @Melchizedek6809
