### ISSUE TITLE
`#version 140` in book codeblocks is hidden by rustdoc

### ISSUE THREAD

**Issue by ChristopherPerry6060** [glium/glium#2053]
Easy fix if the intention is for examples to only be viewable using mdbook.

Could not find contribution guidelines, but am willing to just put a PR as its a really small fix/issue.
[see code block in this section](https://glium.github.io/glium/book/tuto-02-triangle.html#program).

The `#` needs to be escaped so that it is `## version 140`, otherwise Rustdoc / mdbook hides lines starting with `#`. See Rustdoc docs [here](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#hiding-portions-of-the-example)

Could be a source of confusion.

**Comment by est31** [comment]
PRs welcome!

**Comment by ChristopherPerry6060** [comment]
@est31 PR #2054 should fix. Thanks!
