### ISSUE TITLE
Texture sampling mode for Texture2dArray not working!

### ISSUE THREAD

**Issue by jumbledFox** [glium/glium#2064]
I'm passing a Texture2dArray to a shader in the uniforms and I'd like it to be sampled via NEAREST, I've looked at the documentation and it seems that doing it like [this](https://docs.rs/glium/latest/glium/texture/texture2d_array/struct.Texture2dArray.html#method.sampled) is the correct way to do so. My code is exactly the same as the example, however my low resolution textures are still all blurry! This works when I'm sending a 2d texture as opposed to a 2d texture array into the sampler, which is odd.

I think I might be doing something wrong, but I've double checked my code and nothing seems amiss. I'm using the latest version of Glium

Any help would be appreciated!!

**Comment by Melchizedek6809** [comment]
Hey there, could you upload the entire code that's not working? That'd make it nuch easier to pinpoint the problem, since nearest neighbor filtering should generally work for `Texture2dArray` and it might be some strange corner case.

**Comment by jumbledFox** [comment]
Hi! Here's the repo -> https://github.com/jumbledFox/voxel_builder <-

I start with an empty vector of `glium::texture::RawImage2d<'_, u8>`on line 43 of [main.rs](https://github.com/jumbledFox/voxel_builder/blob/main/src/main.rs)
The next instruction creates a voxeldatamanager struct, in which a mutable reference to the images vector is passed

Then, on line 56 of [voxel_data_manager.rs](https://github.com/jumbledFox/voxel_builder/blob/main/src/voxel_data_manager.rs), the images are loaded and added to the images vector.

Back in [main.rs](https://github.com/jumbledFox/voxel_builder/blob/main/src/main.rs), on line 58, i construct the variable texture_2d_array from the vector of images.

I then pass the uniforms to the shader, specifically on line 147 of [main.rs](https://github.com/jumbledFox/voxel_builder/blob/main/src/main.rs)

That's all that goes on with creating and using the Texture2dArray to my knowledge!

**Comment by justincredible** [comment]
On line 147 of `main.rs` the name you are using for the sampler `texture_array` does not match the name of the uniform in `default.frag`.

**Comment by jumbledFox** [comment]
IM SUCH A FOOL! Thanks for pointing that out, sorry if I wasted any time! I really thought I checked everything haha

I'm not able to access my computer to check if fixing it solves the issue but it makes logical sense that it does I'll mark this as closed anyways

Thank you and my apologies!
