### ISSUE TITLE
Is it now recommended or not to continue use glium

### ISSUE THREAD

**Issue by wormtql** [glium/glium#2077]
Since this project is no longer actively developed by original author.

**Comment by notgull** [comment]
The project is still maintained. However, if you're looking for a good, safe, effective GPU interface, you may be more interested in [`wgpu`](https://crates.io/crates/wgpu), as it has the backing of Mozilla and covers more GPU backends than OpenGL.

**Comment by timlathy** [comment]
I'd also add that `glium` has [an excellent tutorial](https://github.com/glium/glium/blob/master/book/tuto-01-getting-started.md) if you're just starting with graphics, and in my limited experience, its API is more straightforward and less verbose than `wgpu`. Don't trust my words, compare the examples yourself, here's drawing a triangle for instance: [`glium`](https://github.com/glium/glium/blob/master/examples/tutorial-02.rs) and [`wgpu`](https://github.com/gfx-rs/wgpu/blob/trunk/examples/hello-triangle/src/main.rs). Note that the latter also requires you to write shaders in WGSL (or deal with translation...)

Don't get me wrong, I totally appreciate `wgpu` for being a true cross-platform general-purpose Rust graphics API, and if you're doing more advanced stuff (or targeting the web), it _is_ a better choice. Personally, though, I use `glium` for my toy projects as I just want to push pixels to my screen with as few complications as possible, and for that I think it's the best option. So far, I haven't encountered any major roadblocks with it :)

P.S. If you do decide to give `glium` a try, be sure to use the version from the master branch (`glium = { git = "https://github.com/glium/glium" }` in your Cargo.toml) as the crates.io version is outdated.

**Comment by est31** [comment]
The question has been answered. I am closing this in favour of #1912.
