### ISSUE TITLE
Draw error from incompatible uniform types

### ISSUE THREAD

**Issue by jasoneveleth** [glium/glium#2088]
Context: Apple M1 Pro, 13.5.2, glium version "0.32.1"

I was working on a large project, and I think I've narrowed down the error. I'm somewhat new at Rust (and very new to OpenGL), so it could be a simple definition mistake. I followed the documentation on how to use a uniform and I have a MRE:

```rust
use glium::index::PrimitiveType;
use glium::program::ProgramCreationInput;
use glium::{VertexBuffer, implement_vertex, Surface, uniform, IndexBuffer, Program};

const CURSOR_VERTEX_SHADER_SOURCE: &str = r#"
    #version 140

    uniform vec4 color;
    in vec2 position;
    out vec4 c;

    void main() {
        gl_Position = vec4(position, 0.0, 1.0);
        c = color;
    }
"#;

const CURSOR_FRAGMENT_SHADER_SOURCE: &str = r#"
    #version 140

    in vec4 c;
    out vec4 color;

    void main() {
        // color = vec4(1.0, 0.2, 0.2, 1.0); // Red color
        color = c;
    }
"#;

#[derive(Copy, Clone, Debug)]
pub struct Vertex {
    position: [f32; 2],
}

implement_vertex!(Vertex, position);

fn main() {
    let wb = glutin::window::WindowBuilder::new();
    let event_loop = glutin::event_loop::EventLoop::new();
    let cb = glutin::ContextBuilder::new().with_srgb(true);
    let window = cb.build_windowed(wb, &event_loop).expect("unable to create window");

    let display = glium::Display::from_gl_window(window).expect("unable to create display");
    let cursor_program = Program::new(
        &display, 
        ProgramCreationInput::SourceCode {
            vertex_shader: CURSOR_VERTEX_SHADER_SOURCE, 
            fragment_shader: CURSOR_FRAGMENT_SHADER_SOURCE, 
            geometry_shader: None,
            tessellation_control_shader: None,
            tessellation_evaluation_shader: None,
            transform_feedback_varyings: None,
            outputs_srgb: true,
            uses_point_size: false,
        }).expect("unable to create program");

    let mut target = display.draw();
    target.clear_color_srgb(0.0, 0.0, 0.0, 0.0);
    
    let uniforms = uniform! { color: [1.0, 1.0, 0.0, 1.0] };

    let f = |x,y| {Vertex{position: [x, y]}};
    let a = [f(0., 0.), f(40., 0.), f(0., 50.), f(40., 50.)];
    let vbuf = VertexBuffer::new(&display, &a).unwrap();
    let ibuf = IndexBuffer::new(&display, PrimitiveType::TrianglesList, &[0u32, 1u32, 2u32, 1u32, 2u32, 3u32]).unwrap();

    // somehow we end up on bind.rs:61 since our array and FloatVec4 are incompatible??
    target.draw(&vbuf, &ibuf, &cursor_program, &uniforms, &Default::default()).unwrap(); // !!!!!
    target.finish().unwrap();
}
```

The panic is coming from the second to last line in the unwrap. I chased down where it was originating and the problem starts on `glium/src/uniforms/bind.rs:61`: `if !value.is_usable_with(&uniform.ty) {`. The value doesn't implement the debug trait but I think it's my array which is supposed to be `[1,1,0,1]`. This seems like it should definitely be good, but it ends up in the else case of the match (line 339). I'd love help narrowing down the issue.

EDIT: The error message is 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UniformTypeMismatch { name: "color", expected: FloatVec4 }', src/main.rs:78:74
```
This code runs fine with `glium::uniforms::EmptyUniforms` and just passing the `vec4` from vertex to fragment without uniform input. And it displays correctly in my much larger original program, so I am pretty certain that the issue is my use of uniforms.

**Comment by jasoneveleth** [comment]
I didn't realize I was on a previous version. I will try updating my large program to see if that fixes the problem.

**Comment by justincredible** [comment]
Rust defaults to `f64` when inferring the type of floating point [literals](https://doc.rust-lang.org/rust-by-example/types/literals.html), so the type of the color uniform is `DoubleVec4` instead of the `FloatVec4` expected by the shaders.

Your MRE can be fixed by specifying the array type:
```rust
let uniforms = uniform! { color: [1.0f32, 1.0, 0.0, 1.0] };
```

**Comment by jasoneveleth** [comment]
Yup that was the problem. Thank you.
