### ISSUE TITLE
release process missing

### ISSUE THREAD

**Issue by waynr** [glium/glium#2092]
It's not clear to me what the process would be to ask for a release[^1] so I thought I would open this issue.

I can see a reasonable-looking pattern in the PR log:

https://github.com/glium/glium/pulls?q=is%3Apr+in%3Atitle%2Cbody+release+is%3Aclosed

The pattern seems to be:

* update `CHANGELOG` based on git log of commits merged since the previous release
* update `Cargo.toml` to reflect new release version

What's not clear is what happens after this commit. I'm not super familiar with github actions but I don't see anything [here](https://github.com/glium/glium/blob/master/.github/workflows/ci.yml) that's recognizable release steps.

If this process were to be documented, someone like myself could do all the menial work of putting together the PRs, then folks who actually understand the code can approve. I'd be happy to propose something!

I realize it's a thankless task to maintain an open source project and there probably isn't someone dedicated to working on it at all time, so i also wanted to thank you! Thanks!

[^1]: the main thing i want in a release is the `winit` dep bump to `0.29` since `glium 0.33`, which appears to already be in master branch

**Comment by est31** [comment]
Hi, the process to ask for a release is to just ask it. Often people ask directly in the threads of the pull requests they would like to use.

It makes sense to make a new release at this point. I will do the steps in the following hours, days. Thanks!
