### ISSUE TITLE
Add depth-stencil attachments to SimpleFramebuffer and MultiOutputFramebuffer

### ISSUE THREAD

**Issue by tomaka** [glium/glium#253]

**Comment by moll** [comment]
I was just looking into how to render some auxiliary data (for mouse picking) in the main rendering call. Seems OpenGL supports rendering to multiple textures and `MultiOutputFramebuffer` seems to be its Glium equivalence. Do I read it correctly that right now using `MultiOutputFramebuffer` "breaks" depth testing?

Thanks!

**Comment by tomaka** [comment]
No, `MultiOutputFramebuffer` doesn't break depth testing. This issue is about depth-stencil attachments combined. Depth attachments and stencil attachments alone do work.

**Comment by moll** [comment]
Superb. Thanks for the quick response!

You wouldn't know how to get access to the default texture and depth buffer (the ones rendered to with `glium::Frame` by default) to pass them into `MultiOutputFramebuffer` along with my own `UnsignedTexture2d` off the top of your head? I'm deep into Glium's source code trying to make head and tails of it and OpenGL at the same time and it's no smooth sailing. :) Thanks again!

**Comment by tomaka** [comment]
That's not possible in OpenGL.

**Comment by moll** [comment]
Ah. That's too bad. How would you roughly go about achieving this — rendering to the main buffer for display and to an auxiliary texture to keep track of rendered model/instance ids? Render to two custom textures and copy from one to the display buffer every frame or assign the second texture as a uniform value and write to that? Don't yet know if a shader _can_ write to a texture passed in as a uniform at all though...

**Comment by tomaka** [comment]
You can't write to a texture passed as uniform. You have to render to a texture and copy.

**Comment by moll** [comment]
Gotcha. Thanks. Hope the copying doesn't revert any speed gains from not rendering twice.

Btw, my first try was to blit from the `MultiOutputFramebuffer` with `blit_from_multioutput_framebuffer` to the display buffer, but that failed with "not yet implemented" on `glium-0.14.0/src/framebuffer/mod.rs:624`. Now figuring out how to blit from the single color texture instead.

Cheers

**Comment by mkovacs** [comment]
I need to create a `SimpleFrameBuffer` that has both a depth and a stencil buffer, but I can't get it to work.

Here are the approaches I've tried:
https://gitlab.com/mkovacs/rust-vr-demo/blob/060f17078c343bd9d5cb6b9368ba07257c258c8d/src/main.rs#L46

Is this use-case supported?
If not, how can I help making it supported?

**Comment by tomaka** [comment]
Ah yeah, the problem is this FIXME here: https://github.com/glium/glium/blob/47d2e2f1d633bc971b1d224fde380b918c098474/src/fbo.rs#L326 :-/

**Comment by mkovacs** [comment]
Hi @tomaka, I have a PR to fix this issue.

My VR project uses a stencil buffer technique for rendering non-Euclidean 3D manifolds, which I'm planning to release on Steam and open source it later this year.
It would be nice if it could depend on `glium` instead of my fork.
Please take a look and consider merging the PR.
